# This file was generated by generate_ld.py

.include "macros.inc"

glabel rspUnknownStart
.incbin "./build/us_1.0/ucode/ucode_unknown.bin"
glabel rspF3DDKRBootStart
.incbin "./build/us_1.0/ucode/ucode_boot.bin"
glabel rspF3DDKRDramStart
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_dram.bin"
glabel rspF3DDKRFifoStart
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_fifo.bin"
glabel rspF3DDKRXbusStart
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_xbus.bin"
glabel rspUnknown2Start
.incbin "./build/us_1.0/ucode/ucode_unknown_2.bin"
