# This file was generated by generate_ld.py

.incbin "./build/us_1.0/ucode/data_f3ddkr_dram.0EA7A0.bin"
.incbin "./build/us_1.0/ucode/data_f3ddkr_fifo.0EAFA0.bin"
.incbin "./build/us_1.0/ucode/data_f3ddkr_xbus.0EB7A0.bin"
.incbin "./build/us_1.0/ucode/data_unknown.0EBFA0.bin"
