# This file was generated by generate_ld.py

.incbin "./build/us_1.0/ucode/ucode_unknown.bin"
.incbin "./build/us_1.0/ucode/ucode_boot.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_dram.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_fifo.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_xbus.bin"
.incbin "./build/us_1.0/ucode/ucode_unknown_2.bin"
