# This file was generated by generate_ld.py

.incbin "./build/us_1.0/ucode/ucode_unknown.0d8200.bin"
.incbin "./build/us_1.0/ucode/ucode_boot.0d90c0.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_dram.0d9190.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_fifo.0da390.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_xbus.0db570.bin"
.incbin "./build/us_1.0/ucode/ucode_unknown.0dc770.bin"
