# This file was generated by generate_ld.py

.incbin "./build/us_1.0/ucode/data_f3ddkr_dram.bin"
.incbin "./build/us_1.0/ucode/data_f3ddkr_fifo.bin"
.incbin "./build/us_1.0/ucode/data_f3ddkr_xbus.bin"
.incbin "./build/us_1.0/ucode/data_unknown.bin"
