# This file was generated by generate_ld.py

.incbin "./build/us_1.0/ucode/ucode_unknown.0D8200.bin"
.incbin "./build/us_1.0/ucode/ucode_boot.0D90C0.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_dram.0D9190.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_fifo.0DA390.bin"
.incbin "./build/us_1.0/ucode/ucode_f3ddkr_xbus.0DB570.bin"
.incbin "./build/us_1.0/ucode/ucode_unknown.0DC770.bin"
