/* The comment below is needed for this file to be picked up by generate_ld */
/* RAM_POS: 0x800C9AD0 */
.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel sqrtf
/* CA6D0 800C9AD0 03E00008 */  jr         $ra
/* CA6D4 800C9AD4 46006004 */   sqrt.s    $f0, $f12
/* CA6D8 800C9AD8 00000000 */  nop
/* CA6DC 800C9ADC 00000000 */  nop
