.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

leaf bcmp
/* CEC50 800CE050 28C10010 */  slti       $at, $a2, 0x10
/* CEC54 800CE054 14200037 */  bnez       $at, .L800CE134
/* CEC58 800CE058 00851026 */   xor       $v0, $a0, $a1
/* CEC5C 800CE05C 30420003 */  andi       $v0, $v0, 0x3
/* CEC60 800CE060 14400019 */  bnez       $v0, .L800CE0C8
/* CEC64 800CE064 0004C023 */   negu      $t8, $a0
/* CEC68 800CE068 33180003 */  andi       $t8, $t8, 0x3
/* CEC6C 800CE06C 13000007 */  beqz       $t8, .L800CE08C
/* CEC70 800CE070 00D83023 */   subu      $a2, $a2, $t8
/* CEC74 800CE074 00601025 */  or         $v0, $v1, $zero
/* CEC78 800CE078 88820000 */  lwl        $v0, 0x0($a0)
/* CEC7C 800CE07C 88A30000 */  lwl        $v1, 0x0($a1)
/* CEC80 800CE080 00982021 */  addu       $a0, $a0, $t8
/* CEC84 800CE084 00B82821 */  addu       $a1, $a1, $t8
/* CEC88 800CE088 14430036 */  bne        $v0, $v1, .L800CE164
.L800CE08C:
/* CEC8C 800CE08C 2401FFFC */   addiu     $at, $zero, -0x4
/* CEC90 800CE090 00C13824 */  and        $a3, $a2, $at
/* CEC94 800CE094 10E00027 */  beqz       $a3, .L800CE134
/* CEC98 800CE098 00C73023 */   subu      $a2, $a2, $a3
/* CEC9C 800CE09C 00E43821 */  addu       $a3, $a3, $a0
/* CECA0 800CE0A0 8C820000 */  lw         $v0, 0x0($a0)
.L800CE0A4:
/* CECA4 800CE0A4 8CA30000 */  lw         $v1, 0x0($a1)
/* CECA8 800CE0A8 24840004 */  addiu      $a0, $a0, 0x4
/* CECAC 800CE0AC 24A50004 */  addiu      $a1, $a1, 0x4
/* CECB0 800CE0B0 1443002C */  bne        $v0, $v1, .L800CE164
/* CECB4 800CE0B4 00000000 */   nop
/* CECB8 800CE0B8 5487FFFA */  bnel       $a0, $a3, .L800CE0A4
/* CECBC 800CE0BC 8C820000 */   lw        $v0, 0x0($a0)
/* CECC0 800CE0C0 1000001C */  b          .L800CE134
/* CECC4 800CE0C4 00000000 */   nop
.L800CE0C8:
/* CECC8 800CE0C8 00053823 */  negu       $a3, $a1
/* CECCC 800CE0CC 30E70003 */  andi       $a3, $a3, 0x3
/* CECD0 800CE0D0 10E0000A */  beqz       $a3, .L800CE0FC
/* CECD4 800CE0D4 00C73023 */   subu      $a2, $a2, $a3
/* CECD8 800CE0D8 00E43821 */  addu       $a3, $a3, $a0
/* CECDC 800CE0DC 90820000 */  lbu        $v0, 0x0($a0)
.L800CE0E0:
/* CECE0 800CE0E0 90A30000 */  lbu        $v1, 0x0($a1)
/* CECE4 800CE0E4 24840001 */  addiu      $a0, $a0, 0x1
/* CECE8 800CE0E8 24A50001 */  addiu      $a1, $a1, 0x1
/* CECEC 800CE0EC 1443001D */  bne        $v0, $v1, .L800CE164
/* CECF0 800CE0F0 00000000 */   nop
/* CECF4 800CE0F4 5487FFFA */  bnel       $a0, $a3, .L800CE0E0
/* CECF8 800CE0F8 90820000 */   lbu       $v0, 0x0($a0)
.L800CE0FC:
/* CECFC 800CE0FC 2401FFFC */  addiu      $at, $zero, -0x4
/* CED00 800CE100 00C13824 */  and        $a3, $a2, $at
/* CED04 800CE104 10E0000B */  beqz       $a3, .L800CE134
/* CED08 800CE108 00C73023 */   subu      $a2, $a2, $a3
/* CED0C 800CE10C 00E43821 */  addu       $a3, $a3, $a0
/* CED10 800CE110 88820000 */  lwl        $v0, 0x0($a0)
.L800CE114:
/* CED14 800CE114 8CA30000 */  lw         $v1, 0x0($a1)
/* CED18 800CE118 98820003 */  lwr        $v0, 0x3($a0)
/* CED1C 800CE11C 24840004 */  addiu      $a0, $a0, 0x4
/* CED20 800CE120 24A50004 */  addiu      $a1, $a1, 0x4
/* CED24 800CE124 1443000F */  bne        $v0, $v1, .L800CE164
/* CED28 800CE128 00000000 */   nop
/* CED2C 800CE12C 5487FFF9 */  bnel       $a0, $a3, .L800CE114
/* CED30 800CE130 88820000 */   lwl       $v0, 0x0($a0)
.L800CE134:
/* CED34 800CE134 18C00009 */  blez       $a2, .L800CE15C
/* CED38 800CE138 00C43821 */   addu      $a3, $a2, $a0
/* CED3C 800CE13C 90820000 */  lbu        $v0, 0x0($a0)
.L800CE140:
/* CED40 800CE140 90A30000 */  lbu        $v1, 0x0($a1)
/* CED44 800CE144 24840001 */  addiu      $a0, $a0, 0x1
/* CED48 800CE148 24A50001 */  addiu      $a1, $a1, 0x1
/* CED4C 800CE14C 14430005 */  bne        $v0, $v1, .L800CE164
/* CED50 800CE150 00000000 */   nop
/* CED54 800CE154 5487FFFA */  bnel       $a0, $a3, .L800CE140
/* CED58 800CE158 90820000 */   lbu       $v0, 0x0($a0)
.L800CE15C:
/* CED5C 800CE15C 03E00008 */  jr         $ra
/* CED60 800CE160 00001025 */   or        $v0, $zero, $zero
.L800CE164:
/* CED64 800CE164 03E00008 */  jr         $ra
/* CED68 800CE168 24020001 */   addiu     $v0, $zero, 0x1
/* CED6C 800CE16C 00000000 */  nop
.end bcmp
