.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf bcopy
/* CA9A0 800C9DA0 10C0001A */  beqz       $a2, .L800C9E0C
/* CA9A4 800C9DA4 00A03825 */   or        $a3, $a1, $zero
/* CA9A8 800C9DA8 10850018 */  beq        $a0, $a1, .L800C9E0C
/* CA9AC 800C9DAC 00A4082A */   slt       $at, $a1, $a0
/* CA9B0 800C9DB0 54200008 */  bnel       $at, $zero, .L800C9DD4
/* CA9B4 800C9DB4 28C10010 */   slti      $at, $a2, 0x10
/* CA9B8 800C9DB8 00861020 */  add        $v0, $a0, $a2 /* handwritten instruction */
/* CA9BC 800C9DBC 00A2082A */  slt        $at, $a1, $v0
/* CA9C0 800C9DC0 50200004 */  beql       $at, $zero, .L800C9DD4
/* CA9C4 800C9DC4 28C10010 */   slti      $at, $a2, 0x10
/* CA9C8 800C9DC8 1000005B */  b          .L800C9F38
/* CA9CC 800C9DCC 28C10010 */   slti      $at, $a2, 0x10
/* CA9D0 800C9DD0 28C10010 */  slti       $at, $a2, 0x10
.L800C9DD4:
/* CA9D4 800C9DD4 14200005 */  bnez       $at, .L800C9DEC
/* CA9D8 800C9DD8 00000000 */   nop
/* CA9DC 800C9DDC 30820003 */  andi       $v0, $a0, 0x3
/* CA9E0 800C9DE0 30A30003 */  andi       $v1, $a1, 0x3
/* CA9E4 800C9DE4 1043000B */  beq        $v0, $v1, .L800C9E14
/* CA9E8 800C9DE8 00000000 */   nop
.L800C9DEC:
/* CA9EC 800C9DEC 10C00007 */  beqz       $a2, .L800C9E0C
/* CA9F0 800C9DF0 00000000 */   nop
/* CA9F4 800C9DF4 00861821 */  addu       $v1, $a0, $a2
.L800C9DF8:
/* CA9F8 800C9DF8 80820000 */  lb         $v0, 0x0($a0)
/* CA9FC 800C9DFC 24840001 */  addiu      $a0, $a0, 0x1
/* CAA00 800C9E00 24A50001 */  addiu      $a1, $a1, 0x1
/* CAA04 800C9E04 1483FFFC */  bne        $a0, $v1, .L800C9DF8
/* CAA08 800C9E08 A0A2FFFF */   sb        $v0, -0x1($a1)
.L800C9E0C:
/* CAA0C 800C9E0C 03E00008 */  jr         $ra
/* CAA10 800C9E10 00E01025 */   or        $v0, $a3, $zero
.L800C9E14:
/* CAA14 800C9E14 10400018 */  beqz       $v0, .L800C9E78
/* CAA18 800C9E18 24010001 */   addiu     $at, $zero, 0x1
/* CAA1C 800C9E1C 1041000F */  beq        $v0, $at, .L800C9E5C
/* CAA20 800C9E20 24010002 */   addiu     $at, $zero, 0x2
/* CAA24 800C9E24 50410008 */  beql       $v0, $at, .L800C9E48
/* CAA28 800C9E28 84820000 */   lh        $v0, 0x0($a0)
/* CAA2C 800C9E2C 80820000 */  lb         $v0, 0x0($a0)
/* CAA30 800C9E30 24840001 */  addiu      $a0, $a0, 0x1
/* CAA34 800C9E34 24A50001 */  addiu      $a1, $a1, 0x1
/* CAA38 800C9E38 24C6FFFF */  addiu      $a2, $a2, -0x1
/* CAA3C 800C9E3C 1000000E */  b          .L800C9E78
/* CAA40 800C9E40 A0A2FFFF */   sb        $v0, -0x1($a1)
/* CAA44 800C9E44 84820000 */  lh         $v0, 0x0($a0)
.L800C9E48:
/* CAA48 800C9E48 24840002 */  addiu      $a0, $a0, 0x2
/* CAA4C 800C9E4C 24A50002 */  addiu      $a1, $a1, 0x2
/* CAA50 800C9E50 24C6FFFE */  addiu      $a2, $a2, -0x2
/* CAA54 800C9E54 10000008 */  b          .L800C9E78
/* CAA58 800C9E58 A4A2FFFE */   sh        $v0, -0x2($a1)
.L800C9E5C:
/* CAA5C 800C9E5C 80820000 */  lb         $v0, 0x0($a0)
/* CAA60 800C9E60 84830001 */  lh         $v1, 0x1($a0)
/* CAA64 800C9E64 24840003 */  addiu      $a0, $a0, 0x3
/* CAA68 800C9E68 24A50003 */  addiu      $a1, $a1, 0x3
/* CAA6C 800C9E6C 24C6FFFD */  addiu      $a2, $a2, -0x3
/* CAA70 800C9E70 A0A2FFFD */  sb         $v0, -0x3($a1)
/* CAA74 800C9E74 A4A3FFFE */  sh         $v1, -0x2($a1)
.L800C9E78:
/* CAA78 800C9E78 28C10020 */  slti       $at, $a2, 0x20
/* CAA7C 800C9E7C 54200016 */  bnel       $at, $zero, .L800C9ED8
/* CAA80 800C9E80 28C10010 */   slti      $at, $a2, 0x10
/* CAA84 800C9E84 8C820000 */  lw         $v0, 0x0($a0)
/* CAA88 800C9E88 8C830004 */  lw         $v1, 0x4($a0)
/* CAA8C 800C9E8C 8C880008 */  lw         $t0, 0x8($a0)
/* CAA90 800C9E90 8C89000C */  lw         $t1, 0xC($a0)
/* CAA94 800C9E94 8C8A0010 */  lw         $t2, 0x10($a0)
/* CAA98 800C9E98 8C8B0014 */  lw         $t3, 0x14($a0)
/* CAA9C 800C9E9C 8C8C0018 */  lw         $t4, 0x18($a0)
/* CAAA0 800C9EA0 8C8D001C */  lw         $t5, 0x1C($a0)
/* CAAA4 800C9EA4 24840020 */  addiu      $a0, $a0, 0x20
/* CAAA8 800C9EA8 24A50020 */  addiu      $a1, $a1, 0x20
/* CAAAC 800C9EAC 24C6FFE0 */  addiu      $a2, $a2, -0x20
/* CAAB0 800C9EB0 ACA2FFE0 */  sw         $v0, -0x20($a1)
/* CAAB4 800C9EB4 ACA3FFE4 */  sw         $v1, -0x1C($a1)
/* CAAB8 800C9EB8 ACA8FFE8 */  sw         $t0, -0x18($a1)
/* CAABC 800C9EBC ACA9FFEC */  sw         $t1, -0x14($a1)
/* CAAC0 800C9EC0 ACAAFFF0 */  sw         $t2, -0x10($a1)
/* CAAC4 800C9EC4 ACABFFF4 */  sw         $t3, -0xC($a1)
/* CAAC8 800C9EC8 ACACFFF8 */  sw         $t4, -0x8($a1)
/* CAACC 800C9ECC 1000FFEA */  b          .L800C9E78
/* CAAD0 800C9ED0 ACADFFFC */   sw        $t5, -0x4($a1)
.L800C9ED4:
/* CAAD4 800C9ED4 28C10010 */  slti       $at, $a2, 0x10
.L800C9ED8:
/* CAAD8 800C9ED8 5420000E */  bnel       $at, $zero, .L800C9F14
/* CAADC 800C9EDC 28C10004 */   slti      $at, $a2, 0x4
/* CAAE0 800C9EE0 8C820000 */  lw         $v0, 0x0($a0)
/* CAAE4 800C9EE4 8C830004 */  lw         $v1, 0x4($a0)
/* CAAE8 800C9EE8 8C880008 */  lw         $t0, 0x8($a0)
/* CAAEC 800C9EEC 8C89000C */  lw         $t1, 0xC($a0)
/* CAAF0 800C9EF0 24840010 */  addiu      $a0, $a0, 0x10
/* CAAF4 800C9EF4 24A50010 */  addiu      $a1, $a1, 0x10
/* CAAF8 800C9EF8 24C6FFF0 */  addiu      $a2, $a2, -0x10
/* CAAFC 800C9EFC ACA2FFF0 */  sw         $v0, -0x10($a1)
/* CAB00 800C9F00 ACA3FFF4 */  sw         $v1, -0xC($a1)
/* CAB04 800C9F04 ACA8FFF8 */  sw         $t0, -0x8($a1)
/* CAB08 800C9F08 1000FFF2 */  b          .L800C9ED4
/* CAB0C 800C9F0C ACA9FFFC */   sw        $t1, -0x4($a1)
.L800C9F10:
/* CAB10 800C9F10 28C10004 */  slti       $at, $a2, 0x4
.L800C9F14:
/* CAB14 800C9F14 1420FFB5 */  bnez       $at, .L800C9DEC
/* CAB18 800C9F18 00000000 */   nop
/* CAB1C 800C9F1C 8C820000 */  lw         $v0, 0x0($a0)
/* CAB20 800C9F20 24840004 */  addiu      $a0, $a0, 0x4
/* CAB24 800C9F24 24A50004 */  addiu      $a1, $a1, 0x4
/* CAB28 800C9F28 24C6FFFC */  addiu      $a2, $a2, -0x4
/* CAB2C 800C9F2C 1000FFF8 */  b          .L800C9F10
/* CAB30 800C9F30 ACA2FFFC */   sw        $v0, -0x4($a1)
/* CAB34 800C9F34 28C10010 */  slti       $at, $a2, 0x10
.L800C9F38:
/* CAB38 800C9F38 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
/* CAB3C 800C9F3C 14200005 */  bnez       $at, .L800C9F54
/* CAB40 800C9F40 00A62820 */   add       $a1, $a1, $a2 /* handwritten instruction */
/* CAB44 800C9F44 30820003 */  andi       $v0, $a0, 0x3
/* CAB48 800C9F48 30A30003 */  andi       $v1, $a1, 0x3
/* CAB4C 800C9F4C 1043000D */  beq        $v0, $v1, .L800C9F84
/* CAB50 800C9F50 00000000 */   nop
.L800C9F54:
/* CAB54 800C9F54 10C0FFAD */  beqz       $a2, .L800C9E0C
/* CAB58 800C9F58 00000000 */   nop
/* CAB5C 800C9F5C 2484FFFF */  addiu      $a0, $a0, -0x1
/* CAB60 800C9F60 24A5FFFF */  addiu      $a1, $a1, -0x1
/* CAB64 800C9F64 00861823 */  subu       $v1, $a0, $a2
.L800C9F68:
/* CAB68 800C9F68 80820000 */  lb         $v0, 0x0($a0)
/* CAB6C 800C9F6C 2484FFFF */  addiu      $a0, $a0, -0x1
/* CAB70 800C9F70 24A5FFFF */  addiu      $a1, $a1, -0x1
/* CAB74 800C9F74 1483FFFC */  bne        $a0, $v1, .L800C9F68
/* CAB78 800C9F78 A0A20001 */   sb        $v0, 0x1($a1)
/* CAB7C 800C9F7C 03E00008 */  jr         $ra
/* CAB80 800C9F80 00E01025 */   or        $v0, $a3, $zero
.L800C9F84:
/* CAB84 800C9F84 10400018 */  beqz       $v0, .L800C9FE8
/* CAB88 800C9F88 24010003 */   addiu     $at, $zero, 0x3
/* CAB8C 800C9F8C 1041000F */  beq        $v0, $at, .L800C9FCC
/* CAB90 800C9F90 24010002 */   addiu     $at, $zero, 0x2
/* CAB94 800C9F94 50410008 */  beql       $v0, $at, .L800C9FB8
/* CAB98 800C9F98 8482FFFE */   lh        $v0, -0x2($a0)
/* CAB9C 800C9F9C 8082FFFF */  lb         $v0, -0x1($a0)
/* CABA0 800C9FA0 2484FFFF */  addiu      $a0, $a0, -0x1
/* CABA4 800C9FA4 24A5FFFF */  addiu      $a1, $a1, -0x1
/* CABA8 800C9FA8 24C6FFFF */  addiu      $a2, $a2, -0x1
/* CABAC 800C9FAC 1000000E */  b          .L800C9FE8
/* CABB0 800C9FB0 A0A20000 */   sb        $v0, 0x0($a1)
/* CABB4 800C9FB4 8482FFFE */  lh         $v0, -0x2($a0)
.L800C9FB8:
/* CABB8 800C9FB8 2484FFFE */  addiu      $a0, $a0, -0x2
/* CABBC 800C9FBC 24A5FFFE */  addiu      $a1, $a1, -0x2
/* CABC0 800C9FC0 24C6FFFE */  addiu      $a2, $a2, -0x2
/* CABC4 800C9FC4 10000008 */  b          .L800C9FE8
/* CABC8 800C9FC8 A4A20000 */   sh        $v0, 0x0($a1)
.L800C9FCC:
/* CABCC 800C9FCC 8082FFFF */  lb         $v0, -0x1($a0)
/* CABD0 800C9FD0 8483FFFD */  lh         $v1, -0x3($a0)
/* CABD4 800C9FD4 2484FFFD */  addiu      $a0, $a0, -0x3
/* CABD8 800C9FD8 24A5FFFD */  addiu      $a1, $a1, -0x3
/* CABDC 800C9FDC 24C6FFFD */  addiu      $a2, $a2, -0x3
/* CABE0 800C9FE0 A0A20002 */  sb         $v0, 0x2($a1)
/* CABE4 800C9FE4 A4A30000 */  sh         $v1, 0x0($a1)
.L800C9FE8:
/* CABE8 800C9FE8 28C10020 */  slti       $at, $a2, 0x20
/* CABEC 800C9FEC 54200016 */  bnel       $at, $zero, .L800CA048
/* CABF0 800C9FF0 28C10010 */   slti      $at, $a2, 0x10
/* CABF4 800C9FF4 8C82FFFC */  lw         $v0, -0x4($a0)
/* CABF8 800C9FF8 8C83FFF8 */  lw         $v1, -0x8($a0)
/* CABFC 800C9FFC 8C88FFF4 */  lw         $t0, -0xC($a0)
/* CAC00 800CA000 8C89FFF0 */  lw         $t1, -0x10($a0)
/* CAC04 800CA004 8C8AFFEC */  lw         $t2, -0x14($a0)
/* CAC08 800CA008 8C8BFFE8 */  lw         $t3, -0x18($a0)
/* CAC0C 800CA00C 8C8CFFE4 */  lw         $t4, -0x1C($a0)
/* CAC10 800CA010 8C8DFFE0 */  lw         $t5, -0x20($a0)
/* CAC14 800CA014 2484FFE0 */  addiu      $a0, $a0, -0x20
/* CAC18 800CA018 24A5FFE0 */  addiu      $a1, $a1, -0x20
/* CAC1C 800CA01C 24C6FFE0 */  addiu      $a2, $a2, -0x20
/* CAC20 800CA020 ACA2001C */  sw         $v0, 0x1C($a1)
/* CAC24 800CA024 ACA30018 */  sw         $v1, 0x18($a1)
/* CAC28 800CA028 ACA80014 */  sw         $t0, 0x14($a1)
/* CAC2C 800CA02C ACA90010 */  sw         $t1, 0x10($a1)
/* CAC30 800CA030 ACAA000C */  sw         $t2, 0xC($a1)
/* CAC34 800CA034 ACAB0008 */  sw         $t3, 0x8($a1)
/* CAC38 800CA038 ACAC0004 */  sw         $t4, 0x4($a1)
/* CAC3C 800CA03C 1000FFEA */  b          .L800C9FE8
/* CAC40 800CA040 ACAD0000 */   sw        $t5, 0x0($a1)
.L800CA044:
/* CAC44 800CA044 28C10010 */  slti       $at, $a2, 0x10
.L800CA048:
/* CAC48 800CA048 5420000E */  bnel       $at, $zero, .L800CA084
/* CAC4C 800CA04C 28C10004 */   slti      $at, $a2, 0x4
/* CAC50 800CA050 8C82FFFC */  lw         $v0, -0x4($a0)
/* CAC54 800CA054 8C83FFF8 */  lw         $v1, -0x8($a0)
/* CAC58 800CA058 8C88FFF4 */  lw         $t0, -0xC($a0)
/* CAC5C 800CA05C 8C89FFF0 */  lw         $t1, -0x10($a0)
/* CAC60 800CA060 2484FFF0 */  addiu      $a0, $a0, -0x10
/* CAC64 800CA064 24A5FFF0 */  addiu      $a1, $a1, -0x10
/* CAC68 800CA068 24C6FFF0 */  addiu      $a2, $a2, -0x10
/* CAC6C 800CA06C ACA2000C */  sw         $v0, 0xC($a1)
/* CAC70 800CA070 ACA30008 */  sw         $v1, 0x8($a1)
/* CAC74 800CA074 ACA80004 */  sw         $t0, 0x4($a1)
/* CAC78 800CA078 1000FFF2 */  b          .L800CA044
/* CAC7C 800CA07C ACA90000 */   sw        $t1, 0x0($a1)
.L800CA080:
/* CAC80 800CA080 28C10004 */  slti       $at, $a2, 0x4
.L800CA084:
/* CAC84 800CA084 1420FFB3 */  bnez       $at, .L800C9F54
/* CAC88 800CA088 00000000 */   nop
/* CAC8C 800CA08C 8C82FFFC */  lw         $v0, -0x4($a0)
/* CAC90 800CA090 2484FFFC */  addiu      $a0, $a0, -0x4
/* CAC94 800CA094 24A5FFFC */  addiu      $a1, $a1, -0x4
/* CAC98 800CA098 24C6FFFC */  addiu      $a2, $a2, -0x4
/* CAC9C 800CA09C 1000FFF8 */  b          .L800CA080
/* CACA0 800CA0A0 ACA20000 */   sw        $v0, 0x0($a1)
.end bcopy
