/* The comment below is needed for this file to be picked up by generate_ld */
/* RAM_POS: 0x800D2560 */

.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
glabel __osDisableInt
/* D3160 800D2560 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
/* D3164 800D2564 2401FFFE */  addiu      $at, $zero, -0x2
/* D3168 800D2568 01014824 */  and        $t1, $t0, $at
/* D316C 800D256C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
/* D3170 800D2570 31020001 */  andi       $v0, $t0, 0x1
/* D3174 800D2574 00000000 */  nop
/* D3178 800D2578 03E00008 */  jr         $ra
/* D317C 800D257C 00000000 */   nop

/* Handwritten function */
glabel __osRestoreInt
/* D3180 800D2580 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
/* D3184 800D2584 01044025 */  or         $t0, $t0, $a0
/* D3188 800D2588 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
/* D318C 800D258C 00000000 */  nop
/* D3190 800D2590 00000000 */  nop
/* D3194 800D2594 03E00008 */  jr         $ra
/* D3198 800D2598 00000000 */   nop
/* D319C 800D259C 00000000 */  nop
