/* The comment below is needed for this file to be picked up by generate_ld */
/* RAM_POS: 0x800D4580 */

.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

glabel __osSetFpcCsr
/* D5180 800D4580 4442F800 */  cfc1       $v0, $31
/* D5184 800D4584 44C4F800 */  ctc1       $a0, $31
/* D5188 800D4588 03E00008 */  jr         $ra
/* D518C 800D458C 00000000 */   nop
