/* The comment below is needed for this file to be picked up by generate_ld */
/* RAM_POS: 0x800D2470 */

#include "types.h"
#include "macros.h"

GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/func_800D2470.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osPiCreateAccessQueue.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osGetThreadPri.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osDisableInt.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osRestoreInt.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/D_800D25A0.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/D_800D2680.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/D_800D2760.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osViInit.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/func_800D2C60.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osDequeueThread.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osExceptionPreamble.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osException.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/send_mesg.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osEnqueueAndYield.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osEnqueueThread.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osPopThread.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osDispatchThread.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/D_800D35A0.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osProbeTLB.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/func_800D3670.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osJamMesg.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osPiGetCmdQueue.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/func_800D3820.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/_Putfld.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/_Printf.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osSetSR.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osGetSR.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osSetFpcCsr.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osSiRawReadIo.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/__osSiRawWriteIo.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osWritebackDCache.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osWritebackICache.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osMapTLBRdb.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/osPiRawWriteIo.s")
GLOBAL_ASM("lib/asm/non_matchings/unknown_0D3020/func_800D47F0.s")
