.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .bss

glabel __osThreadSave
.space 0x1B0

.section .data

glabel __osHwIntTable
.word 0
.word 0
.word 0
.word 0
.word 0

.section .rodata

glabel __osIntOffTable
.byte 0x00
.byte 0x14
.byte 0x18
.byte 0x18
.byte 0x1C
.byte 0x1C
.byte 0x1C
.byte 0x1C
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x20
.byte 0x00
.byte 0x04
.byte 0x08
.byte 0x08
.byte 0x0C
.byte 0x0C
.byte 0x0C
.byte 0x0C
.byte 0x10
.byte 0x10
.byte 0x10
.byte 0x10
.byte 0x10
.byte 0x10
.byte 0x10
.byte 0x10

glabel __osIntTable
.word .L800D3168
.word .L800D3130
.word .L800D3110
.word .L800D2F74
.word .L800D2F20
.word .L800D30B4
.word .L800D2EE8
.word .L800D2EF4
.word .L800D2F00

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

leaf __osExceptionPreamble
/* D38B0 800D2CB0 3C1A800D */  lui        $k0, %hi(__osException) /* handwritten instruction */
/* D38B4 800D2CB4 275A2CC0 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
/* D38B8 800D2CB8 03400008 */  jr         $k0
/* D38BC 800D2CBC 00000000 */   nop
.end __osExceptionPreamble

leaf __osException
/* D38C0 800D2CC0 3C1A8013 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
/* D38C4 800D2CC4 275AD240 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
/* D38C8 800D2CC8 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
/* D38CC 800D2CCC 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
/* D38D0 800D2CD0 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
/* D38D4 800D2CD4 2401FFFC */  addiu      $at, $zero, -0x4
/* D38D8 800D2CD8 0361D824 */  and        $k1, $k1, $at
/* D38DC 800D2CDC 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
/* D38E0 800D2CE0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
/* D38E4 800D2CE4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
/* D38E8 800D2CE8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
/* D38EC 800D2CEC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
/* D38F0 800D2CF0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
/* D38F4 800D2CF4 03404025 */  or         $t0, $k0, $zero
/* D38F8 800D2CF8 3C1A800E */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
/* D38FC 800D2CFC 8F5A4890 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
/* D3900 800D2D00 DD090020 */  ld         $t1, 0x20($t0)
/* D3904 800D2D04 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
/* D3908 800D2D08 DD090118 */  ld         $t1, 0x118($t0)
/* D390C 800D2D0C FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
/* D3910 800D2D10 DD090058 */  ld         $t1, 0x58($t0)
/* D3914 800D2D14 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
/* D3918 800D2D18 DD090060 */  ld         $t1, 0x60($t0)
/* D391C 800D2D1C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
/* D3920 800D2D20 DD090068 */  ld         $t1, 0x68($t0)
/* D3924 800D2D24 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
/* D3928 800D2D28 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D392C 800D2D2C 00004012 */  mflo       $t0
/* D3930 800D2D30 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
/* D3934 800D2D34 00004010 */  mfhi       $t0
/* D3938 800D2D38 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D393C 800D2D3C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
/* D3940 800D2D40 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
/* D3944 800D2D44 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
/* D3948 800D2D48 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
/* D394C 800D2D4C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
/* D3950 800D2D50 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
/* D3954 800D2D54 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
/* D3958 800D2D58 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
/* D395C 800D2D5C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
/* D3960 800D2D60 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
/* D3964 800D2D64 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
/* D3968 800D2D68 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
/* D396C 800D2D6C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
/* D3970 800D2D70 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
/* D3974 800D2D74 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
/* D3978 800D2D78 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
/* D397C 800D2D7C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
/* D3980 800D2D80 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
/* D3984 800D2D84 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
/* D3988 800D2D88 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
/* D398C 800D2D8C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
/* D3990 800D2D90 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
/* D3994 800D2D94 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
/* D3998 800D2D98 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
/* D399C 800D2D9C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
/* D39A0 800D2DA0 1120000D */  beqz       $t1, .L800D2DD8
/* D39A4 800D2DA4 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
/* D39A8 800D2DA8 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* D39AC 800D2DAC 250838AC */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* D39B0 800D2DB0 8D080000 */  lw         $t0, 0x0($t0)
/* D39B4 800D2DB4 2401FFFF */  addiu      $at, $zero, -0x1
/* D39B8 800D2DB8 01014026 */  xor        $t0, $t0, $at
/* D39BC 800D2DBC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D39C0 800D2DC0 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D39C4 800D2DC4 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D39C8 800D2DC8 01284825 */  or         $t1, $t1, $t0
/* D39CC 800D2DCC 0361D824 */  and        $k1, $k1, $at
/* D39D0 800D2DD0 0369D825 */  or         $k1, $k1, $t1
/* D39D4 800D2DD4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
.L800D2DD8:
/* D39D8 800D2DD8 3C09A430 */  lui        $t1, %hi(MI_INTR_MASK_REG)
/* D39DC 800D2DDC 8D29000C */  lw         $t1, %lo(MI_INTR_MASK_REG)($t1)
/* D39E0 800D2DE0 1120000B */  beqz       $t1, .L800D2E10
/* D39E4 800D2DE4 00000000 */   nop
/* D39E8 800D2DE8 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* D39EC 800D2DEC 250838AC */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* D39F0 800D2DF0 8D080000 */  lw         $t0, 0x0($t0)
/* D39F4 800D2DF4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
/* D39F8 800D2DF8 2401FFFF */  addiu      $at, $zero, -0x1
/* D39FC 800D2DFC 00084402 */  srl        $t0, $t0, 16
/* D3A00 800D2E00 01014026 */  xor        $t0, $t0, $at
/* D3A04 800D2E04 3108003F */  andi       $t0, $t0, 0x3F
/* D3A08 800D2E08 010C4024 */  and        $t0, $t0, $t4
/* D3A0C 800D2E0C 01284825 */  or         $t1, $t1, $t0
.L800D2E10:
/* D3A10 800D2E10 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
/* D3A14 800D2E14 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
/* D3A18 800D2E18 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
/* D3A1C 800D2E1C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
/* D3A20 800D2E20 11000014 */  beqz       $t0, .L800D2E74
/* D3A24 800D2E24 00000000 */   nop
/* D3A28 800D2E28 4448F800 */  cfc1       $t0, $31
/* D3A2C 800D2E2C 00000000 */  nop
/* D3A30 800D2E30 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
/* D3A34 800D2E34 F7400130 */  sdc1       $f0, 0x130($k0)
/* D3A38 800D2E38 F7420138 */  sdc1       $f2, 0x138($k0)
/* D3A3C 800D2E3C F7440140 */  sdc1       $f4, 0x140($k0)
/* D3A40 800D2E40 F7460148 */  sdc1       $f6, 0x148($k0)
/* D3A44 800D2E44 F7480150 */  sdc1       $f8, 0x150($k0)
/* D3A48 800D2E48 F74A0158 */  sdc1       $f10, 0x158($k0)
/* D3A4C 800D2E4C F74C0160 */  sdc1       $f12, 0x160($k0)
/* D3A50 800D2E50 F74E0168 */  sdc1       $f14, 0x168($k0)
/* D3A54 800D2E54 F7500170 */  sdc1       $f16, 0x170($k0)
/* D3A58 800D2E58 F7520178 */  sdc1       $f18, 0x178($k0)
/* D3A5C 800D2E5C F7540180 */  sdc1       $f20, 0x180($k0)
/* D3A60 800D2E60 F7560188 */  sdc1       $f22, 0x188($k0)
/* D3A64 800D2E64 F7580190 */  sdc1       $f24, 0x190($k0)
/* D3A68 800D2E68 F75A0198 */  sdc1       $f26, 0x198($k0)
/* D3A6C 800D2E6C F75C01A0 */  sdc1       $f28, 0x1A0($k0)
/* D3A70 800D2E70 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
.L800D2E74:
/* D3A74 800D2E74 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
/* D3A78 800D2E78 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
/* D3A7C 800D2E7C 24090002 */  addiu      $t1, $zero, 0x2
/* D3A80 800D2E80 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
/* D3A84 800D2E84 3109007C */  andi       $t1, $t0, 0x7C
/* D3A88 800D2E88 240A0024 */  addiu      $t2, $zero, 0x24
/* D3A8C 800D2E8C 112A00B0 */  beq        $t1, $t2, .L800D3150
/* D3A90 800D2E90 00000000 */   nop
/* D3A94 800D2E94 240A002C */  addiu      $t2, $zero, 0x2C
/* D3A98 800D2E98 112A00FF */  beq        $t1, $t2, handle_CpU
/* D3A9C 800D2E9C 00000000 */   nop
/* D3AA0 800D2EA0 240A0000 */  addiu      $t2, $zero, 0x0
/* D3AA4 800D2EA4 152A00C3 */  bne        $t1, $t2, .L800D31B4
/* D3AA8 800D2EA8 00000000 */   nop
/* D3AAC 800D2EAC 03688024 */  and        $s0, $k1, $t0
.L800D2EB0:
/* D3AB0 800D2EB0 3209FF00 */  andi       $t1, $s0, 0xFF00
/* D3AB4 800D2EB4 00095302 */  srl        $t2, $t1, 12
/* D3AB8 800D2EB8 15400003 */  bnez       $t2, .L800D2EC8
/* D3ABC 800D2EBC 00000000 */   nop
/* D3AC0 800D2EC0 00095202 */  srl        $t2, $t1, 8
/* D3AC4 800D2EC4 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
.L800D2EC8:
/* D3AC8 800D2EC8 3C01800F */  lui        $at, %hi(__osIntOffTable)
/* D3ACC 800D2ECC 002A0821 */  addu       $at, $at, $t2
/* D3AD0 800D2ED0 902A9670 */  lbu        $t2, %lo(__osIntOffTable)($at)
/* D3AD4 800D2ED4 3C01800F */  lui        $at, %hi(__osIntTable)
/* D3AD8 800D2ED8 002A0821 */  addu       $at, $at, $t2
/* D3ADC 800D2EDC 8C2A9690 */  lw         $t2, %lo(__osIntTable)($at)
/* D3AE0 800D2EE0 01400008 */  jr         $t2
/* D3AE4 800D2EE4 00000000 */   nop
glabel .L800D2EE8
/* D3AE8 800D2EE8 2401DFFF */  addiu      $at, $zero, -0x2001
/* D3AEC 800D2EEC 1000FFF0 */  b          .L800D2EB0
/* D3AF0 800D2EF0 02018024 */   and       $s0, $s0, $at
glabel .L800D2EF4
/* D3AF4 800D2EF4 2401BFFF */  addiu      $at, $zero, -0x4001
/* D3AF8 800D2EF8 1000FFED */  b          .L800D2EB0
/* D3AFC 800D2EFC 02018024 */   and       $s0, $s0, $at
glabel .L800D2F00
/* D3B00 800D2F00 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
/* D3B04 800D2F04 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
/* D3B08 800D2F08 0C034C79 */  jal        send_mesg
/* D3B0C 800D2F0C 24040018 */   addiu     $a0, $zero, 0x18
/* D3B10 800D2F10 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
/* D3B14 800D2F14 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
/* D3B18 800D2F18 1000FFE5 */  b          .L800D2EB0
/* D3B1C 800D2F1C 02018024 */   and       $s0, $s0, $at
glabel .L800D2F20
/* D3B20 800D2F20 2401F7FF */  addiu      $at, $zero, -0x801
/* D3B24 800D2F24 02018024 */  and        $s0, $s0, $at
/* D3B28 800D2F28 240A0004 */  addiu      $t2, $zero, 0x4
/* D3B2C 800D2F2C 3C01800E */  lui        $at, %hi(__osHwIntTable)
/* D3B30 800D2F30 002A0821 */  addu       $at, $at, $t2
/* D3B34 800D2F34 8C2A48A0 */  lw         $t2, %lo(__osHwIntTable)($at)
/* D3B38 800D2F38 3C1D8013 */  lui        $sp, %hi(leoDiskStack)
/* D3B3C 800D2F3C 27BDAAE0 */  addiu      $sp, $sp, %lo(leoDiskStack)
/* D3B40 800D2F40 24040010 */  addiu      $a0, $zero, 0x10
/* D3B44 800D2F44 11400007 */  beqz       $t2, .L800D2F64
/* D3B48 800D2F48 27BD0FF0 */   addiu     $sp, $sp, 0xFF0
/* D3B4C 800D2F4C 0140F809 */  jalr       $t2
/* D3B50 800D2F50 00000000 */   nop
/* D3B54 800D2F54 10400003 */  beqz       $v0, .L800D2F64
/* D3B58 800D2F58 00000000 */   nop
/* D3B5C 800D2F5C 10000082 */  b          .L800D3168
/* D3B60 800D2F60 00000000 */   nop
.L800D2F64:
/* D3B64 800D2F64 0C034C79 */  jal        send_mesg
/* D3B68 800D2F68 00000000 */   nop
/* D3B6C 800D2F6C 1000FFD0 */  b          .L800D2EB0
/* D3B70 800D2F70 00000000 */   nop
glabel .L800D2F74
/* D3B74 800D2F74 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* D3B78 800D2F78 250838AC */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* D3B7C 800D2F7C 8D080000 */  lw         $t0, 0x0($t0)
/* D3B80 800D2F80 3C11A430 */  lui        $s1, %hi(MI_INTR_REG)
/* D3B84 800D2F84 8E310008 */  lw         $s1, %lo(MI_INTR_REG)($s1)
/* D3B88 800D2F88 00084402 */  srl        $t0, $t0, 16
/* D3B8C 800D2F8C 02288824 */  and        $s1, $s1, $t0
/* D3B90 800D2F90 32290001 */  andi       $t1, $s1, 0x1
/* D3B94 800D2F94 11200013 */  beqz       $t1, .L800D2FE4
/* D3B98 800D2F98 00000000 */   nop
/* D3B9C 800D2F9C 3C0CA404 */  lui        $t4, %hi(SP_STATUS_REG)
/* D3BA0 800D2FA0 8D8C0010 */  lw         $t4, %lo(SP_STATUS_REG)($t4)
/* D3BA4 800D2FA4 24090008 */  addiu      $t1, $zero, 0x8
/* D3BA8 800D2FA8 3C01A404 */  lui        $at, %hi(SP_STATUS_REG)
/* D3BAC 800D2FAC 318C0300 */  andi       $t4, $t4, 0x300
/* D3BB0 800D2FB0 3231003E */  andi       $s1, $s1, 0x3E
/* D3BB4 800D2FB4 11800007 */  beqz       $t4, .L800D2FD4
/* D3BB8 800D2FB8 AC290010 */   sw        $t1, %lo(SP_STATUS_REG)($at)
/* D3BBC 800D2FBC 0C034C79 */  jal        send_mesg
/* D3BC0 800D2FC0 24040020 */   addiu     $a0, $zero, 0x20
/* D3BC4 800D2FC4 12200038 */  beqz       $s1, .L800D30A8
/* D3BC8 800D2FC8 00000000 */   nop
/* D3BCC 800D2FCC 10000005 */  b          .L800D2FE4
/* D3BD0 800D2FD0 00000000 */   nop
.L800D2FD4:
/* D3BD4 800D2FD4 0C034C79 */  jal        send_mesg
/* D3BD8 800D2FD8 24040058 */   addiu     $a0, $zero, 0x58
/* D3BDC 800D2FDC 12200032 */  beqz       $s1, .L800D30A8
/* D3BE0 800D2FE0 00000000 */   nop
.L800D2FE4:
/* D3BE4 800D2FE4 32290008 */  andi       $t1, $s1, 0x8
/* D3BE8 800D2FE8 11200007 */  beqz       $t1, .L800D3008
/* D3BEC 800D2FEC 3C01A440 */   lui       $at, %hi(VI_V_CURRENT_LINE_REG)
/* D3BF0 800D2FF0 32310037 */  andi       $s1, $s1, 0x37
/* D3BF4 800D2FF4 AC200010 */  sw         $zero, %lo(VI_V_CURRENT_LINE_REG)($at)
/* D3BF8 800D2FF8 0C034C79 */  jal        send_mesg
/* D3BFC 800D2FFC 24040038 */   addiu     $a0, $zero, 0x38
/* D3C00 800D3000 12200029 */  beqz       $s1, .L800D30A8
/* D3C04 800D3004 00000000 */   nop
.L800D3008:
/* D3C08 800D3008 32290004 */  andi       $t1, $s1, 0x4
/* D3C0C 800D300C 11200009 */  beqz       $t1, .L800D3034
/* D3C10 800D3010 00000000 */   nop
/* D3C14 800D3014 24090001 */  addiu      $t1, $zero, 0x1
/* D3C18 800D3018 3C01A450 */  lui        $at, %hi(AI_STATUS_REG)
/* D3C1C 800D301C 3231003B */  andi       $s1, $s1, 0x3B
/* D3C20 800D3020 AC29000C */  sw         $t1, %lo(AI_STATUS_REG)($at)
/* D3C24 800D3024 0C034C79 */  jal        send_mesg
/* D3C28 800D3028 24040030 */   addiu     $a0, $zero, 0x30
/* D3C2C 800D302C 1220001E */  beqz       $s1, .L800D30A8
/* D3C30 800D3030 00000000 */   nop
.L800D3034:
/* D3C34 800D3034 32290002 */  andi       $t1, $s1, 0x2
/* D3C38 800D3038 11200007 */  beqz       $t1, .L800D3058
/* D3C3C 800D303C 3C01A480 */   lui       $at, %hi(SI_STATUS_REG)
/* D3C40 800D3040 3231003D */  andi       $s1, $s1, 0x3D
/* D3C44 800D3044 AC200018 */  sw         $zero, %lo(SI_STATUS_REG)($at)
/* D3C48 800D3048 0C034C79 */  jal        send_mesg
/* D3C4C 800D304C 24040028 */   addiu     $a0, $zero, 0x28
/* D3C50 800D3050 12200015 */  beqz       $s1, .L800D30A8
/* D3C54 800D3054 00000000 */   nop
.L800D3058:
/* D3C58 800D3058 32290010 */  andi       $t1, $s1, 0x10
/* D3C5C 800D305C 11200009 */  beqz       $t1, .L800D3084
/* D3C60 800D3060 00000000 */   nop
/* D3C64 800D3064 24090002 */  addiu      $t1, $zero, 0x2
/* D3C68 800D3068 3C01A460 */  lui        $at, %hi(PI_STATUS_REG)
/* D3C6C 800D306C 3231002F */  andi       $s1, $s1, 0x2F
/* D3C70 800D3070 AC290010 */  sw         $t1, %lo(PI_STATUS_REG)($at)
/* D3C74 800D3074 0C034C79 */  jal        send_mesg
/* D3C78 800D3078 24040040 */   addiu     $a0, $zero, 0x40
/* D3C7C 800D307C 1220000A */  beqz       $s1, .L800D30A8
/* D3C80 800D3080 00000000 */   nop
.L800D3084:
/* D3C84 800D3084 32290020 */  andi       $t1, $s1, 0x20
/* D3C88 800D3088 11200007 */  beqz       $t1, .L800D30A8
/* D3C8C 800D308C 00000000 */   nop
/* D3C90 800D3090 24090800 */  addiu      $t1, $zero, 0x800
/* D3C94 800D3094 3C01A430 */  lui        $at, %hi(MI_MODE_REG)
/* D3C98 800D3098 3231001F */  andi       $s1, $s1, 0x1F
/* D3C9C 800D309C AC290000 */  sw         $t1, %lo(MI_MODE_REG)($at)
/* D3CA0 800D30A0 0C034C79 */  jal        send_mesg
/* D3CA4 800D30A4 24040048 */   addiu     $a0, $zero, 0x48
.L800D30A8:
/* D3CA8 800D30A8 2401FBFF */  addiu      $at, $zero, -0x401
/* D3CAC 800D30AC 1000FF80 */  b          .L800D2EB0
/* D3CB0 800D30B0 02018024 */   and       $s0, $s0, $at
glabel .L800D30B4
/* D3CB4 800D30B4 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D3CB8 800D30B8 2401EFFF */  addiu      $at, $zero, -0x1001
/* D3CBC 800D30BC 3C09800E */  lui        $t1, %hi(__osShutdown)
/* D3CC0 800D30C0 0361D824 */  and        $k1, $k1, $at
/* D3CC4 800D30C4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
/* D3CC8 800D30C8 252938A8 */  addiu      $t1, $t1, %lo(__osShutdown)
/* D3CCC 800D30CC 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3CD0 800D30D0 11400003 */  beqz       $t2, .L800D30E0
/* D3CD4 800D30D4 2401EFFF */   addiu     $at, $zero, -0x1001
/* D3CD8 800D30D8 10000023 */  b          .L800D3168
/* D3CDC 800D30DC 02018024 */   and       $s0, $s0, $at
.L800D30E0:
/* D3CE0 800D30E0 240A0001 */  addiu      $t2, $zero, 0x1
/* D3CE4 800D30E4 AD2A0000 */  sw         $t2, 0x0($t1)
/* D3CE8 800D30E8 0C034C79 */  jal        send_mesg
/* D3CEC 800D30EC 24040070 */   addiu     $a0, $zero, 0x70
/* D3CF0 800D30F0 3C0A800E */  lui        $t2, %hi(__osRunQueue)
/* D3CF4 800D30F4 8D4A4888 */  lw         $t2, %lo(__osRunQueue)($t2)
/* D3CF8 800D30F8 2401EFFF */  addiu      $at, $zero, -0x1001
/* D3CFC 800D30FC 02018024 */  and        $s0, $s0, $at
/* D3D00 800D3100 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
/* D3D04 800D3104 0361D824 */  and        $k1, $k1, $at
/* D3D08 800D3108 10000017 */  b          .L800D3168
/* D3D0C 800D310C AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
glabel .L800D3110
/* D3D10 800D3110 2401FDFF */  addiu      $at, $zero, -0x201
/* D3D14 800D3114 01014024 */  and        $t0, $t0, $at
/* D3D18 800D3118 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
/* D3D1C 800D311C 0C034C79 */  jal        send_mesg
/* D3D20 800D3120 24040008 */   addiu     $a0, $zero, 0x8
/* D3D24 800D3124 2401FDFF */  addiu      $at, $zero, -0x201
/* D3D28 800D3128 1000FF61 */  b          .L800D2EB0
/* D3D2C 800D312C 02018024 */   and       $s0, $s0, $at
glabel .L800D3130
/* D3D30 800D3130 2401FEFF */  addiu      $at, $zero, -0x101
/* D3D34 800D3134 01014024 */  and        $t0, $t0, $at
/* D3D38 800D3138 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
/* D3D3C 800D313C 0C034C79 */  jal        send_mesg
/* D3D40 800D3140 24040000 */   addiu     $a0, $zero, 0x0
/* D3D44 800D3144 2401FEFF */  addiu      $at, $zero, -0x101
/* D3D48 800D3148 1000FF59 */  b          .L800D2EB0
/* D3D4C 800D314C 02018024 */   and       $s0, $s0, $at
.L800D3150:
/* D3D50 800D3150 24090001 */  addiu      $t1, $zero, 0x1
/* D3D54 800D3154 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
/* D3D58 800D3158 0C034C79 */  jal        send_mesg
/* D3D5C 800D315C 24040050 */   addiu     $a0, $zero, 0x50
/* D3D60 800D3160 10000001 */  b          .L800D3168
/* D3D64 800D3164 00000000 */   nop
glabel .L800D3168
/* D3D68 800D3168 3C0A800E */  lui        $t2, %hi(__osRunQueue)
/* D3D6C 800D316C 8D4A4888 */  lw         $t2, %lo(__osRunQueue)($t2)
/* D3D70 800D3170 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
/* D3D74 800D3174 8D4B0004 */  lw         $t3, 0x4($t2)
/* D3D78 800D3178 012B082A */  slt        $at, $t1, $t3
/* D3D7C 800D317C 10200007 */  beqz       $at, .L800D319C
/* D3D80 800D3180 00000000 */   nop
/* D3D84 800D3184 3C04800E */  lui        $a0, %hi(__osRunQueue)
/* D3D88 800D3188 03402825 */  or         $a1, $k0, $zero
/* D3D8C 800D318C 0C034CF3 */  jal        __osEnqueueThread
/* D3D90 800D3190 24844888 */   addiu     $a0, $a0, %lo(__osRunQueue)
/* D3D94 800D3194 08034D09 */  j          __osDispatchThread
/* D3D98 800D3198 00000000 */   nop
.L800D319C:
/* D3D9C 800D319C 3C09800E */  lui        $t1, %hi(__osRunQueue)
/* D3DA0 800D31A0 25294888 */  addiu      $t1, $t1, %lo(__osRunQueue)
/* D3DA4 800D31A4 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3DA8 800D31A8 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
/* D3DAC 800D31AC 08034D09 */  j          __osDispatchThread
/* D3DB0 800D31B0 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
.L800D31B4:
/* D3DB4 800D31B4 3C01800E */  lui        $at, %hi(__osFaultedThread)
/* D3DB8 800D31B8 AC3A4894 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
/* D3DBC 800D31BC 24090001 */  addiu      $t1, $zero, 0x1
/* D3DC0 800D31C0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
/* D3DC4 800D31C4 24090002 */  addiu      $t1, $zero, 0x2
/* D3DC8 800D31C8 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
/* D3DCC 800D31CC 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
/* D3DD0 800D31D0 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
/* D3DD4 800D31D4 0C034C79 */  jal        send_mesg
/* D3DD8 800D31D8 24040060 */   addiu     $a0, $zero, 0x60
/* D3DDC 800D31DC 08034D09 */  j          __osDispatchThread
/* D3DE0 800D31E0 00000000 */   nop
.end __osException

leaf send_mesg
/* D3DE4 800D31E4 3C0A8013 */  lui        $t2, %hi(__osEventStateTab)
/* D3DE8 800D31E8 254ACCD0 */  addiu      $t2, $t2, %lo(__osEventStateTab)
/* D3DEC 800D31EC 01445021 */  addu       $t2, $t2, $a0
/* D3DF0 800D31F0 8D490000 */  lw         $t1, 0x0($t2)
/* D3DF4 800D31F4 03E09025 */  or         $s2, $ra, $zero
/* D3DF8 800D31F8 11200025 */  beqz       $t1, .L800D3290
/* D3DFC 800D31FC 00000000 */   nop
/* D3E00 800D3200 8D2B0008 */  lw         $t3, 0x8($t1)
/* D3E04 800D3204 8D2C0010 */  lw         $t4, 0x10($t1)
/* D3E08 800D3208 016C082A */  slt        $at, $t3, $t4
/* D3E0C 800D320C 10200020 */  beqz       $at, .L800D3290
/* D3E10 800D3210 00000000 */   nop
/* D3E14 800D3214 8D2D000C */  lw         $t5, 0xC($t1)
/* D3E18 800D3218 01AB6821 */  addu       $t5, $t5, $t3
/* D3E1C 800D321C 01AC001A */  div        $zero, $t5, $t4
/* D3E20 800D3220 15800002 */  bnez       $t4, .L800D322C
/* D3E24 800D3224 00000000 */   nop
/* D3E28 800D3228 0007000D */  break      7
.L800D322C:
/* D3E2C 800D322C 2401FFFF */  addiu      $at, $zero, -0x1
/* D3E30 800D3230 15810004 */  bne        $t4, $at, .L800D3244
/* D3E34 800D3234 3C018000 */   lui       $at, (0x80000000 >> 16)
/* D3E38 800D3238 15A10002 */  bne        $t5, $at, .L800D3244
/* D3E3C 800D323C 00000000 */   nop
/* D3E40 800D3240 0006000D */  break      6
.L800D3244:
/* D3E44 800D3244 8D2C0014 */  lw         $t4, 0x14($t1)
/* D3E48 800D3248 00006810 */  mfhi       $t5
/* D3E4C 800D324C 000D6880 */  sll        $t5, $t5, 2
/* D3E50 800D3250 018D6021 */  addu       $t4, $t4, $t5
/* D3E54 800D3254 8D4D0004 */  lw         $t5, 0x4($t2)
/* D3E58 800D3258 256A0001 */  addiu      $t2, $t3, 0x1
/* D3E5C 800D325C AD8D0000 */  sw         $t5, 0x0($t4)
/* D3E60 800D3260 AD2A0008 */  sw         $t2, 0x8($t1)
/* D3E64 800D3264 8D2A0000 */  lw         $t2, 0x0($t1)
/* D3E68 800D3268 8D4B0000 */  lw         $t3, 0x0($t2)
/* D3E6C 800D326C 11600008 */  beqz       $t3, .L800D3290
/* D3E70 800D3270 00000000 */   nop
/* D3E74 800D3274 0C034D05 */  jal        __osPopThread
/* D3E78 800D3278 01202025 */   or        $a0, $t1, $zero
/* D3E7C 800D327C 00405025 */  or         $t2, $v0, $zero
/* D3E80 800D3280 3C04800E */  lui        $a0, %hi(__osRunQueue)
/* D3E84 800D3284 01402825 */  or         $a1, $t2, $zero
/* D3E88 800D3288 0C034CF3 */  jal        __osEnqueueThread
/* D3E8C 800D328C 24844888 */   addiu     $a0, $a0, %lo(__osRunQueue)
.L800D3290:
/* D3E90 800D3290 02400008 */  jr         $s2
/* D3E94 800D3294 00000000 */   nop
.end send_mesg

leaf handle_CpU
/* D3E98 800D3298 3C013000 */  lui        $at, (0x30000000 >> 16)
/* D3E9C 800D329C 01014824 */  and        $t1, $t0, $at
/* D3EA0 800D32A0 00094F02 */  srl        $t1, $t1, 28
/* D3EA4 800D32A4 240A0001 */  addiu      $t2, $zero, 0x1
/* D3EA8 800D32A8 152AFFC2 */  bne        $t1, $t2, .L800D31B4
/* D3EAC 800D32AC 00000000 */   nop
/* D3EB0 800D32B0 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D3EB4 800D32B4 3C012000 */  lui        $at, (0x20000000 >> 16)
/* D3EB8 800D32B8 24090001 */  addiu      $t1, $zero, 0x1
/* D3EBC 800D32BC 0361D825 */  or         $k1, $k1, $at
/* D3EC0 800D32C0 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
/* D3EC4 800D32C4 1000FFB5 */  b          .L800D319C
/* D3EC8 800D32C8 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
.end handle_CpU

leaf __osEnqueueAndYield
/* D3ECC 800D32CC 3C05800E */  lui        $a1, %hi(__osRunningThread)
/* D3ED0 800D32D0 8CA54890 */  lw         $a1, %lo(__osRunningThread)($a1)
/* D3ED4 800D32D4 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
/* D3ED8 800D32D8 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
/* D3EDC 800D32DC 35080002 */  ori        $t0, $t0, 0x2
/* D3EE0 800D32E0 ACA80118 */  sw         $t0, 0x118($a1)
/* D3EE4 800D32E4 FCB00098 */  sd         $s0, 0x98($a1)
/* D3EE8 800D32E8 FCB100A0 */  sd         $s1, 0xA0($a1)
/* D3EEC 800D32EC FCB200A8 */  sd         $s2, 0xA8($a1)
/* D3EF0 800D32F0 FCB300B0 */  sd         $s3, 0xB0($a1)
/* D3EF4 800D32F4 FCB400B8 */  sd         $s4, 0xB8($a1)
/* D3EF8 800D32F8 FCB500C0 */  sd         $s5, 0xC0($a1)
/* D3EFC 800D32FC FCB600C8 */  sd         $s6, 0xC8($a1)
/* D3F00 800D3300 FCB700D0 */  sd         $s7, 0xD0($a1)
/* D3F04 800D3304 FCBC00E8 */  sd         $gp, 0xE8($a1)
/* D3F08 800D3308 FCBD00F0 */  sd         $sp, 0xF0($a1)
/* D3F0C 800D330C FCBE00F8 */  sd         $fp, 0xF8($a1)
/* D3F10 800D3310 FCBF0100 */  sd         $ra, 0x100($a1)
/* D3F14 800D3314 13600009 */  beqz       $k1, .L800D333C /* handwritten instruction */
/* D3F18 800D3318 ACBF011C */   sw        $ra, 0x11C($a1)
/* D3F1C 800D331C 445BF800 */  cfc1       $k1, $31
/* D3F20 800D3320 F4B40180 */  sdc1       $f20, 0x180($a1)
/* D3F24 800D3324 F4B60188 */  sdc1       $f22, 0x188($a1)
/* D3F28 800D3328 F4B80190 */  sdc1       $f24, 0x190($a1)
/* D3F2C 800D332C F4BA0198 */  sdc1       $f26, 0x198($a1)
/* D3F30 800D3330 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
/* D3F34 800D3334 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
/* D3F38 800D3338 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
.L800D333C:
/* D3F3C 800D333C 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
/* D3F40 800D3340 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D3F44 800D3344 1120000D */  beqz       $t1, .L800D337C
/* D3F48 800D3348 00000000 */   nop
/* D3F4C 800D334C 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* D3F50 800D3350 250838AC */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* D3F54 800D3354 8D080000 */  lw         $t0, 0x0($t0)
/* D3F58 800D3358 2401FFFF */  addiu      $at, $zero, -0x1
/* D3F5C 800D335C 01014026 */  xor        $t0, $t0, $at
/* D3F60 800D3360 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D3F64 800D3364 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D3F68 800D3368 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D3F6C 800D336C 01284825 */  or         $t1, $t1, $t0
/* D3F70 800D3370 0361D824 */  and        $k1, $k1, $at
/* D3F74 800D3374 0369D825 */  or         $k1, $k1, $t1
/* D3F78 800D3378 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
.L800D337C:
/* D3F7C 800D337C 3C1BA430 */  lui        $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
/* D3F80 800D3380 8F7B000C */  lw         $k1, %lo(MI_INTR_MASK_REG)($k1) /* handwritten instruction */
/* D3F84 800D3384 1360000B */  beqz       $k1, .L800D33B4 /* handwritten instruction */
/* D3F88 800D3388 00000000 */   nop
/* D3F8C 800D338C 3C1A800E */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
/* D3F90 800D3390 275A38AC */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
/* D3F94 800D3394 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
/* D3F98 800D3398 8CA80128 */  lw         $t0, 0x128($a1)
/* D3F9C 800D339C 2401FFFF */  addiu      $at, $zero, -0x1
/* D3FA0 800D33A0 001AD402 */  srl        $k0, $k0, 16
/* D3FA4 800D33A4 0341D026 */  xor        $k0, $k0, $at
/* D3FA8 800D33A8 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
/* D3FAC 800D33AC 0348D024 */  and        $k0, $k0, $t0
/* D3FB0 800D33B0 037AD825 */  or         $k1, $k1, $k0
.L800D33B4:
/* D3FB4 800D33B4 10800003 */  beqz       $a0, .L800D33C4
/* D3FB8 800D33B8 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
/* D3FBC 800D33BC 0C034CF3 */  jal        __osEnqueueThread
/* D3FC0 800D33C0 00000000 */   nop
.L800D33C4:
/* D3FC4 800D33C4 08034D09 */  j          __osDispatchThread
/* D3FC8 800D33C8 00000000 */   nop
.end __osEnqueueAndYield

leaf __osEnqueueThread
/* D3FCC 800D33CC 8C980000 */  lw         $t8, 0x0($a0)
/* D3FD0 800D33D0 8CAF0004 */  lw         $t7, 0x4($a1)
/* D3FD4 800D33D4 0080C825 */  or         $t9, $a0, $zero
/* D3FD8 800D33D8 8F0E0004 */  lw         $t6, 0x4($t8)
/* D3FDC 800D33DC 01CF082A */  slt        $at, $t6, $t7
/* D3FE0 800D33E0 14200007 */  bnez       $at, .L800D3400
/* D3FE4 800D33E4 00000000 */   nop
.L800D33E8:
/* D3FE8 800D33E8 0300C825 */  or         $t9, $t8, $zero
/* D3FEC 800D33EC 8F180000 */  lw         $t8, 0x0($t8)
/* D3FF0 800D33F0 8F0E0004 */  lw         $t6, 0x4($t8)
/* D3FF4 800D33F4 01CF082A */  slt        $at, $t6, $t7
/* D3FF8 800D33F8 1020FFFB */  beqz       $at, .L800D33E8
/* D3FFC 800D33FC 00000000 */   nop
.L800D3400:
/* D4000 800D3400 8F380000 */  lw         $t8, 0x0($t9)
/* D4004 800D3404 ACB80000 */  sw         $t8, 0x0($a1)
/* D4008 800D3408 AF250000 */  sw         $a1, 0x0($t9)
/* D400C 800D340C 03E00008 */  jr         $ra
/* D4010 800D3410 ACA40008 */   sw        $a0, 0x8($a1)
.end __osEnqueueThread

leaf __osPopThread
/* D4014 800D3414 8C820000 */  lw         $v0, 0x0($a0)
/* D4018 800D3418 8C590000 */  lw         $t9, 0x0($v0)
/* D401C 800D341C 03E00008 */  jr         $ra
/* D4020 800D3420 AC990000 */   sw        $t9, 0x0($a0)
.end __osPopThread

leaf __osDispatchThread
/* D4024 800D3424 3C04800E */  lui        $a0, %hi(__osRunQueue)
/* D4028 800D3428 0C034D05 */  jal        __osPopThread
/* D402C 800D342C 24844888 */   addiu     $a0, $a0, %lo(__osRunQueue)
/* D4030 800D3430 3C01800E */  lui        $at, %hi(__osRunningThread)
/* D4034 800D3434 AC224890 */  sw         $v0, %lo(__osRunningThread)($at)
/* D4038 800D3438 24080004 */  addiu      $t0, $zero, 0x4
/* D403C 800D343C A4480010 */  sh         $t0, 0x10($v0)
/* D4040 800D3440 0040D025 */  or         $k0, $v0, $zero
/* D4044 800D3444 3C08800E */  lui        $t0, %hi(__OSGlobalIntMask)
/* D4048 800D3448 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
/* D404C 800D344C 250838AC */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
/* D4050 800D3450 8D080000 */  lw         $t0, 0x0($t0)
/* D4054 800D3454 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
/* D4058 800D3458 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
/* D405C 800D345C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
/* D4060 800D3460 3108FF00 */  andi       $t0, $t0, 0xFF00
/* D4064 800D3464 01284824 */  and        $t1, $t1, $t0
/* D4068 800D3468 0361D824 */  and        $k1, $k1, $at
/* D406C 800D346C 0369D825 */  or         $k1, $k1, $t1
/* D4070 800D3470 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
/* D4074 800D3474 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
/* D4078 800D3478 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
/* D407C 800D347C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
/* D4080 800D3480 03600013 */  mtlo       $k1
/* D4084 800D3484 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
/* D4088 800D3488 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
/* D408C 800D348C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
/* D4090 800D3490 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
/* D4094 800D3494 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
/* D4098 800D3498 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
/* D409C 800D349C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
/* D40A0 800D34A0 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
/* D40A4 800D34A4 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
/* D40A8 800D34A8 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
/* D40AC 800D34AC DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
/* D40B0 800D34B0 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
/* D40B4 800D34B4 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
/* D40B8 800D34B8 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
/* D40BC 800D34BC DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
/* D40C0 800D34C0 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
/* D40C4 800D34C4 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
/* D40C8 800D34C8 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
/* D40CC 800D34CC DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
/* D40D0 800D34D0 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
/* D40D4 800D34D4 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
/* D40D8 800D34D8 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
/* D40DC 800D34DC DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
/* D40E0 800D34E0 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
/* D40E4 800D34E4 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
/* D40E8 800D34E8 03600011 */  mthi       $k1
/* D40EC 800D34EC DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
/* D40F0 800D34F0 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
/* D40F4 800D34F4 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
/* D40F8 800D34F8 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
/* D40FC 800D34FC 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
/* D4100 800D3500 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
/* D4104 800D3504 13600013 */  beqz       $k1, .L800D3554 /* handwritten instruction */
/* D4108 800D3508 00000000 */   nop
/* D410C 800D350C 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
/* D4110 800D3510 44DBF800 */  ctc1       $k1, $31
/* D4114 800D3514 D7400130 */  ldc1       $f0, 0x130($k0)
/* D4118 800D3518 D7420138 */  ldc1       $f2, 0x138($k0)
/* D411C 800D351C D7440140 */  ldc1       $f4, 0x140($k0)
/* D4120 800D3520 D7460148 */  ldc1       $f6, 0x148($k0)
/* D4124 800D3524 D7480150 */  ldc1       $f8, 0x150($k0)
/* D4128 800D3528 D74A0158 */  ldc1       $f10, 0x158($k0)
/* D412C 800D352C D74C0160 */  ldc1       $f12, 0x160($k0)
/* D4130 800D3530 D74E0168 */  ldc1       $f14, 0x168($k0)
/* D4134 800D3534 D7500170 */  ldc1       $f16, 0x170($k0)
/* D4138 800D3538 D7520178 */  ldc1       $f18, 0x178($k0)
/* D413C 800D353C D7540180 */  ldc1       $f20, 0x180($k0)
/* D4140 800D3540 D7560188 */  ldc1       $f22, 0x188($k0)
/* D4144 800D3544 D7580190 */  ldc1       $f24, 0x190($k0)
/* D4148 800D3548 D75A0198 */  ldc1       $f26, 0x198($k0)
/* D414C 800D354C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
/* D4150 800D3550 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
.L800D3554:
/* D4154 800D3554 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
/* D4158 800D3558 3C1A800E */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
/* D415C 800D355C 275A38AC */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
/* D4160 800D3560 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
/* D4164 800D3564 001AD402 */  srl        $k0, $k0, 16
/* D4168 800D3568 037AD824 */  and        $k1, $k1, $k0
/* D416C 800D356C 001BD840 */  sll        $k1, $k1, 1
/* D4170 800D3570 3C1A800F */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
/* D4174 800D3574 275A94D0 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
/* D4178 800D3578 037AD821 */  addu       $k1, $k1, $k0
/* D417C 800D357C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
/* D4180 800D3580 3C1AA430 */  lui        $k0, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
/* D4184 800D3584 275A000C */  addiu      $k0, $k0, %lo(MI_INTR_MASK_REG) /* handwritten instruction */
/* D4188 800D3588 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
/* D418C 800D358C 00000000 */  nop
/* D4190 800D3590 00000000 */  nop
/* D4194 800D3594 00000000 */  nop
/* D4198 800D3598 00000000 */  nop
/* D419C 800D359C 42000018 */  eret /* handwritten instruction */
.end __osDispatchThread

leaf __osCleanupThread
/* D41A0 800D35A0 0C035980 */  jal        osDestroyThread
/* D41A4 800D35A4 00002025 */   or        $a0, $zero, $zero
.end __osCleanupThread
