.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf osMapTLBRdb
/* D5330 800D4730 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* D5334 800D4734 2409001F */  addiu      $t1, $zero, 0x1F
/* D5338 800D4738 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
/* D533C 800D473C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
/* D5340 800D4740 240A0017 */  addiu      $t2, $zero, 0x17
/* D5344 800D4744 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
/* D5348 800D4748 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* D534C 800D474C 3C098000 */  lui        $t1, (0x80000000 >> 16)
/* D5350 800D4750 00095982 */  srl        $t3, $t1, 6
/* D5354 800D4754 016A5825 */  or         $t3, $t3, $t2
/* D5358 800D4758 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
/* D535C 800D475C 24090001 */  addiu      $t1, $zero, 0x1
/* D5360 800D4760 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
/* D5364 800D4764 00000000 */  nop
/* D5368 800D4768 42000002 */  tlbwi /* handwritten instruction */
/* D536C 800D476C 00000000 */  nop
/* D5370 800D4770 00000000 */  nop
/* D5374 800D4774 00000000 */  nop
/* D5378 800D4778 00000000 */  nop
/* D537C 800D477C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* D5380 800D4780 03E00008 */  jr         $ra
/* D5384 800D4784 00000000 */   nop
.end osMapTLBRdb
