.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf __osProbeTLB
/* D41B0 800D35B0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
/* D41B4 800D35B4 310900FF */  andi       $t1, $t0, 0xFF
/* D41B8 800D35B8 2401E000 */  addiu      $at, $zero, -0x2000
/* D41BC 800D35BC 00815024 */  and        $t2, $a0, $at
/* D41C0 800D35C0 012A4825 */  or         $t1, $t1, $t2
/* D41C4 800D35C4 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
/* D41C8 800D35C8 00000000 */  nop
/* D41CC 800D35CC 00000000 */  nop
/* D41D0 800D35D0 00000000 */  nop
/* D41D4 800D35D4 42000008 */  tlbp /* handwritten instruction */
/* D41D8 800D35D8 00000000 */  nop
/* D41DC 800D35DC 00000000 */  nop
/* D41E0 800D35E0 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
/* D41E4 800D35E4 3C018000 */  lui        $at, (0x80000000 >> 16)
/* D41E8 800D35E8 01615824 */  and        $t3, $t3, $at
/* D41EC 800D35EC 1560001A */  bnez       $t3, .L800D3658
/* D41F0 800D35F0 00000000 */   nop
/* D41F4 800D35F4 42000001 */  tlbr /* handwritten instruction */
/* D41F8 800D35F8 00000000 */  nop
/* D41FC 800D35FC 00000000 */  nop
/* D4200 800D3600 00000000 */  nop
/* D4204 800D3604 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
/* D4208 800D3608 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
/* D420C 800D360C 000B5842 */  srl        $t3, $t3, 1
/* D4210 800D3610 01646024 */  and        $t4, $t3, $a0
/* D4214 800D3614 15800004 */  bnez       $t4, .L800D3628
/* D4218 800D3618 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
/* D421C 800D361C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
/* D4220 800D3620 10000002 */  b          .L800D362C
/* D4224 800D3624 00000000 */   nop
.L800D3628:
/* D4228 800D3628 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
.L800D362C:
/* D422C 800D362C 304D0002 */  andi       $t5, $v0, 0x2
/* D4230 800D3630 11A00009 */  beqz       $t5, .L800D3658
/* D4234 800D3634 00000000 */   nop
/* D4238 800D3638 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
/* D423C 800D363C 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
/* D4240 800D3640 00411024 */  and        $v0, $v0, $at
/* D4244 800D3644 00021180 */  sll        $v0, $v0, 6
/* D4248 800D3648 008B6824 */  and        $t5, $a0, $t3
/* D424C 800D364C 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
/* D4250 800D3650 10000002 */  b          .L800D365C
/* D4254 800D3654 00000000 */   nop
.L800D3658:
/* D4258 800D3658 2402FFFF */  addiu      $v0, $zero, -0x1
.L800D365C:
/* D425C 800D365C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
/* D4260 800D3660 03E00008 */  jr         $ra
/* D4264 800D3664 00000000 */   nop
.end __osProbeTLB
