.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf __osSetSR
mtc0       $a0, $12 /* handwritten instruction */
nop
jr         $ra
nop
.end __osSetSR
