.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf osWritebackDCacheAll
/* D24A0 800D18A0 3C088000 */  lui        $t0, 0x8000
/* D24A4 800D18A4 240A2000 */  addiu      $t2, $zero, 0x2000
/* D24A8 800D18A8 010A4821 */  addu       $t1, $t0, $t2
/* D24AC 800D18AC 2529FFF0 */  addiu      $t1, $t1, -0x10
.L800D18B0:
/* D24B0 800D18B0 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* D24B4 800D18B4 0109082B */  sltu       $at, $t0, $t1
/* D24B8 800D18B8 1420FFFD */  bnez       $at, .L800D18B0
/* D24BC 800D18BC 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D24C0 800D18C0 03E00008 */  jr         $ra
/* D24C4 800D18C4 00000000 */   nop
.end osWritebackDCacheAll
