.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

/* Handwritten function */
leaf osWritebackDCache
/* D5230 800D4630 18A00011 */  blez       $a1, .L800D4678
/* D5234 800D4634 00000000 */   nop
/* D5238 800D4638 240B2000 */  addiu      $t3, $zero, 0x2000
/* D523C 800D463C 00AB082B */  sltu       $at, $a1, $t3
/* D5240 800D4640 1020000F */  beqz       $at, .L800D4680
/* D5244 800D4644 00000000 */   nop
/* D5248 800D4648 00804025 */  or         $t0, $a0, $zero
/* D524C 800D464C 00854821 */  addu       $t1, $a0, $a1
/* D5250 800D4650 0109082B */  sltu       $at, $t0, $t1
/* D5254 800D4654 10200008 */  beqz       $at, .L800D4678
/* D5258 800D4658 00000000 */   nop
/* D525C 800D465C 310A000F */  andi       $t2, $t0, 0xF
/* D5260 800D4660 2529FFF0 */  addiu      $t1, $t1, -0x10
/* D5264 800D4664 010A4023 */  subu       $t0, $t0, $t2
.L800D4668:
/* D5268 800D4668 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
/* D526C 800D466C 0109082B */  sltu       $at, $t0, $t1
/* D5270 800D4670 1420FFFD */  bnez       $at, .L800D4668
/* D5274 800D4674 25080010 */   addiu     $t0, $t0, 0x10
.L800D4678:
/* D5278 800D4678 03E00008 */  jr         $ra
/* D527C 800D467C 00000000 */   nop
.L800D4680:
/* D5280 800D4680 3C088000 */  lui        $t0, 0x8000
/* D5284 800D4684 010B4821 */  addu       $t1, $t0, $t3
/* D5288 800D4688 2529FFF0 */  addiu      $t1, $t1, -0x10
.L800D468C:
/* D528C 800D468C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
/* D5290 800D4690 0109082B */  sltu       $at, $t0, $t1
/* D5294 800D4694 1420FFFD */  bnez       $at, .L800D468C
/* D5298 800D4698 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
/* D529C 800D469C 03E00008 */  jr         $ra
/* D52A0 800D46A0 00000000 */   nop
.end osWritebackDCache
