.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

glabel gzip_border
.byte 16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15

glabel gzip_cplens
.half 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0

glabel gzip_cplext
.byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0, 99, 99

glabel gzip_cpdist
.half 1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577

glabel gzip_cpdext
.byte 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13

glabel gzip_mask_bits
.half 0x0000, 0x0001, 0x0003, 0x0007, 0x000f, 0x001f, 0x003f, 0x007f, 0x00ff, 0x01ff, 0x03ff, 0x07ff, 0x0fff, 0x1fff, 0x3fff, 0x7fff, 0xffff

.section .text, "ax"

/* Generated by spimdisasm 1.30.0 */

leaf gzip_inflate_block
/* C74C0 800C68C0 3C0B8013 */  lui        $t3, %hi(gzip_num_bits)
/* C74C4 800C68C4 8D6BAAD4 */  lw         $t3, %lo(gzip_num_bits)($t3)
/* C74C8 800C68C8 3C018013 */  lui        $at, %hi(gHuftTablePos)
/* C74CC 800C68CC AC20AAD8 */  sw         $zero, %lo(gHuftTablePos)($at)
/* C74D0 800C68D0 24080001 */  addiu      $t0, $zero, 0x1
/* C74D4 800C68D4 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* C74D8 800C68D8 3C0C800E */  lui        $t4, %hi(gzip_inflate_input)
/* C74DC 800C68DC 3C0A8013 */  lui        $t2, %hi(gzip_bit_buffer)
/* C74E0 800C68E0 0168082B */  sltu       $at, $t3, $t0
/* C74E4 800C68E4 AFBF001C */  sw         $ra, 0x1C($sp)
/* C74E8 800C68E8 AFB00018 */  sw         $s0, 0x18($sp)
/* C74EC 800C68EC 8D8C3768 */  lw         $t4, %lo(gzip_inflate_input)($t4)
/* C74F0 800C68F0 10200008 */  beqz       $at, .L800C6914
/* C74F4 800C68F4 8D4AAAD0 */   lw        $t2, %lo(gzip_bit_buffer)($t2)
.L800C68F8:
/* C74F8 800C68F8 91820000 */  lbu        $v0, 0x0($t4)
/* C74FC 800C68FC 258C0001 */  addiu      $t4, $t4, 0x1
/* C7500 800C6900 01621004 */  sllv       $v0, $v0, $t3
/* C7504 800C6904 256B0008 */  addiu      $t3, $t3, 0x8
/* C7508 800C6908 0168082A */  slt        $at, $t3, $t0
/* C750C 800C690C 1420FFFA */  bnez       $at, .L800C68F8
/* C7510 800C6910 01425025 */   or        $t2, $t2, $v0
.L800C6914:
/* C7514 800C6914 31500001 */  andi       $s0, $t2, 0x1
/* C7518 800C6918 010A5006 */  srlv       $t2, $t2, $t0
/* C751C 800C691C 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7520 800C6920 24080002 */  addiu      $t0, $zero, 0x2
/* C7524 800C6924 0168082B */  sltu       $at, $t3, $t0
/* C7528 800C6928 10200008 */  beqz       $at, .L800C694C
/* C752C 800C692C 00000000 */   nop
.L800C6930:
/* C7530 800C6930 91820000 */  lbu        $v0, 0x0($t4)
/* C7534 800C6934 258C0001 */  addiu      $t4, $t4, 0x1
/* C7538 800C6938 01621004 */  sllv       $v0, $v0, $t3
/* C753C 800C693C 256B0008 */  addiu      $t3, $t3, 0x8
/* C7540 800C6940 0168082A */  slt        $at, $t3, $t0
/* C7544 800C6944 1420FFFA */  bnez       $at, .L800C6930
/* C7548 800C6948 01425025 */   or        $t2, $t2, $v0
.L800C694C:
/* C754C 800C694C 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7550 800C6950 31490003 */  andi       $t1, $t2, 0x3
/* C7554 800C6954 AC2C3768 */  sw         $t4, %lo(gzip_inflate_input)($at)
/* C7558 800C6958 010A5006 */  srlv       $t2, $t2, $t0
/* C755C 800C695C 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7560 800C6960 AC2AAAD0 */  sw         $t2, %lo(gzip_bit_buffer)($at)
/* C7564 800C6964 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
/* C7568 800C6968 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C756C 800C696C AC2BAAD4 */  sw         $t3, %lo(gzip_num_bits)($at)
/* C7570 800C6970 24010002 */  addiu      $at, $zero, 0x2
/* C7574 800C6974 1121000B */  beq        $t1, $at, .L800C69A4
/* C7578 800C6978 24010001 */   addiu     $at, $zero, 0x1
/* C757C 800C697C 11210005 */  beq        $t1, $at, .L800C6994
/* C7580 800C6980 00000000 */   nop
/* C7584 800C6984 0C031BCD */  jal        gzip_inflate_stored
/* C7588 800C6988 00000000 */   nop
/* C758C 800C698C 08031A6B */  j          .L800C69AC
/* C7590 800C6990 00000000 */   nop
.L800C6994:
/* C7594 800C6994 0C031B77 */  jal        gzip_inflate_fixed
/* C7598 800C6998 00000000 */   nop
/* C759C 800C699C 08031A6B */  j          .L800C69AC
/* C75A0 800C69A0 00000000 */   nop
.L800C69A4:
/* C75A4 800C69A4 0C031A71 */  jal        gzip_inflate_dynamic
/* C75A8 800C69A8 00000000 */   nop
.L800C69AC:
/* C75AC 800C69AC 8FBF001C */  lw         $ra, 0x1C($sp)
/* C75B0 800C69B0 24020001 */  addiu      $v0, $zero, 0x1
/* C75B4 800C69B4 00501022 */  sub        $v0, $v0, $s0 /* handwritten instruction */
/* C75B8 800C69B8 8FB00018 */  lw         $s0, 0x18($sp)
/* C75BC 800C69BC 03E00008 */  jr         $ra
/* C75C0 800C69C0 27BD0020 */   addiu     $sp, $sp, 0x20
.end gzip_inflate_block

leaf gzip_inflate_dynamic
/* C75C4 800C69C4 27BDFAC0 */  addiu      $sp, $sp, -0x540
/* C75C8 800C69C8 AFB30028 */  sw         $s3, 0x28($sp)
/* C75CC 800C69CC 3C138013 */  lui        $s3, %hi(gzip_num_bits)
/* C75D0 800C69D0 8E73AAD4 */  lw         $s3, %lo(gzip_num_bits)($s3)
/* C75D4 800C69D4 AFB4002C */  sw         $s4, 0x2C($sp)
/* C75D8 800C69D8 AFB20024 */  sw         $s2, 0x24($sp)
/* C75DC 800C69DC 24080005 */  addiu      $t0, $zero, 0x5
/* C75E0 800C69E0 3C14800E */  lui        $s4, %hi(gzip_inflate_input)
/* C75E4 800C69E4 3C128013 */  lui        $s2, %hi(gzip_bit_buffer)
/* C75E8 800C69E8 0268082B */  sltu       $at, $s3, $t0
/* C75EC 800C69EC AFBF0030 */  sw         $ra, 0x30($sp)
/* C75F0 800C69F0 AFB10020 */  sw         $s1, 0x20($sp)
/* C75F4 800C69F4 AFB0001C */  sw         $s0, 0x1C($sp)
/* C75F8 800C69F8 8E943768 */  lw         $s4, %lo(gzip_inflate_input)($s4)
/* C75FC 800C69FC 10200008 */  beqz       $at, .L800C6A20
/* C7600 800C6A00 8E52AAD0 */   lw        $s2, %lo(gzip_bit_buffer)($s2)
.L800C6A04:
/* C7604 800C6A04 92820000 */  lbu        $v0, 0x0($s4)
/* C7608 800C6A08 26940001 */  addiu      $s4, $s4, 0x1
/* C760C 800C6A0C 02621004 */  sllv       $v0, $v0, $s3
/* C7610 800C6A10 26730008 */  addiu      $s3, $s3, 0x8
/* C7614 800C6A14 0268082A */  slt        $at, $s3, $t0
/* C7618 800C6A18 1420FFFA */  bnez       $at, .L800C6A04
/* C761C 800C6A1C 02429025 */   or        $s2, $s2, $v0
.L800C6A20:
/* C7620 800C6A20 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7624 800C6A24 3251001F */  andi       $s1, $s2, 0x1F
/* C7628 800C6A28 0268082B */  sltu       $at, $s3, $t0
/* C762C 800C6A2C 26310101 */  addiu      $s1, $s1, 0x101
/* C7630 800C6A30 10200008 */  beqz       $at, .L800C6A54
/* C7634 800C6A34 01129006 */   srlv      $s2, $s2, $t0
.L800C6A38:
/* C7638 800C6A38 92820000 */  lbu        $v0, 0x0($s4)
/* C763C 800C6A3C 26940001 */  addiu      $s4, $s4, 0x1
/* C7640 800C6A40 02621004 */  sllv       $v0, $v0, $s3
/* C7644 800C6A44 26730008 */  addiu      $s3, $s3, 0x8
/* C7648 800C6A48 0268082A */  slt        $at, $s3, $t0
/* C764C 800C6A4C 1420FFFA */  bnez       $at, .L800C6A38
/* C7650 800C6A50 02429025 */   or        $s2, $s2, $v0
.L800C6A54:
/* C7654 800C6A54 3250001F */  andi       $s0, $s2, 0x1F
/* C7658 800C6A58 01129006 */  srlv       $s2, $s2, $t0
/* C765C 800C6A5C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7660 800C6A60 24080004 */  addiu      $t0, $zero, 0x4
/* C7664 800C6A64 0268082B */  sltu       $at, $s3, $t0
/* C7668 800C6A68 10200008 */  beqz       $at, .L800C6A8C
/* C766C 800C6A6C 26100001 */   addiu     $s0, $s0, 0x1
.L800C6A70:
/* C7670 800C6A70 92820000 */  lbu        $v0, 0x0($s4)
/* C7674 800C6A74 26940001 */  addiu      $s4, $s4, 0x1
/* C7678 800C6A78 02621004 */  sllv       $v0, $v0, $s3
/* C767C 800C6A7C 26730008 */  addiu      $s3, $s3, 0x8
/* C7680 800C6A80 0268082A */  slt        $at, $s3, $t0
/* C7684 800C6A84 1420FFFA */  bnez       $at, .L800C6A70
/* C7688 800C6A88 02429025 */   or        $s2, $s2, $v0
.L800C6A8C:
/* C768C 800C6A8C 324A000F */  andi       $t2, $s2, 0xF
/* C7690 800C6A90 254A0004 */  addiu      $t2, $t2, 0x4
/* C7694 800C6A94 3C19800F */  lui        $t9, %hi(gzip_border)
/* C7698 800C6A98 01129006 */  srlv       $s2, $s2, $t0
/* C769C 800C6A9C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C76A0 800C6AA0 000A4825 */  or         $t1, $zero, $t2
/* C76A4 800C6AA4 273993C0 */  addiu      $t9, $t9, %lo(gzip_border)
/* C76A8 800C6AA8 11400019 */  beqz       $t2, .L800C6B10
/* C76AC 800C6AAC 23AF0044 */   addi      $t7, $sp, 0x44 /* handwritten instruction */
.L800C6AB0:
/* C76B0 800C6AB0 24080003 */  addiu      $t0, $zero, 0x3
/* C76B4 800C6AB4 0268082B */  sltu       $at, $s3, $t0
/* C76B8 800C6AB8 50200009 */  beql       $at, $zero, .L800C6AE0
/* C76BC 800C6ABC 93230000 */   lbu       $v1, 0x0($t9)
.L800C6AC0:
/* C76C0 800C6AC0 92820000 */  lbu        $v0, 0x0($s4)
/* C76C4 800C6AC4 26940001 */  addiu      $s4, $s4, 0x1
/* C76C8 800C6AC8 02621004 */  sllv       $v0, $v0, $s3
/* C76CC 800C6ACC 26730008 */  addiu      $s3, $s3, 0x8
/* C76D0 800C6AD0 0268082A */  slt        $at, $s3, $t0
/* C76D4 800C6AD4 1420FFFA */  bnez       $at, .L800C6AC0
/* C76D8 800C6AD8 02429025 */   or        $s2, $s2, $v0
/* C76DC 800C6ADC 93230000 */  lbu        $v1, 0x0($t9)
.L800C6AE0:
/* C76E0 800C6AE0 32420007 */  andi       $v0, $s2, 0x7
/* C76E4 800C6AE4 254AFFFF */  addiu      $t2, $t2, -0x1
/* C76E8 800C6AE8 00031880 */  sll        $v1, $v1, 2
/* C76EC 800C6AEC 006F1821 */  addu       $v1, $v1, $t7
/* C76F0 800C6AF0 AC620000 */  sw         $v0, 0x0($v1)
/* C76F4 800C6AF4 01129006 */  srlv       $s2, $s2, $t0
/* C76F8 800C6AF8 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C76FC 800C6AFC 1540FFEC */  bnez       $t2, .L800C6AB0
/* C7700 800C6B00 27390001 */   addiu     $t9, $t9, 0x1
/* C7704 800C6B04 2D210013 */  sltiu      $at, $t1, 0x13
/* C7708 800C6B08 5020000A */  beql       $at, $zero, .L800C6B34
/* C770C 800C6B0C 240D0007 */   addiu     $t5, $zero, 0x7
.L800C6B10:
/* C7710 800C6B10 93230000 */  lbu        $v1, 0x0($t9)
/* C7714 800C6B14 25290001 */  addiu      $t1, $t1, 0x1
/* C7718 800C6B18 29210013 */  slti       $at, $t1, 0x13
/* C771C 800C6B1C 00031880 */  sll        $v1, $v1, 2
/* C7720 800C6B20 006F1821 */  addu       $v1, $v1, $t7
/* C7724 800C6B24 AC600000 */  sw         $zero, 0x0($v1)
/* C7728 800C6B28 1420FFF9 */  bnez       $at, .L800C6B10
/* C772C 800C6B2C 27390001 */   addiu     $t9, $t9, 0x1
/* C7730 800C6B30 240D0007 */  addiu      $t5, $zero, 0x7
.L800C6B34:
/* C7734 800C6B34 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7738 800C6B38 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C773C 800C6B3C AFAD0038 */  sw         $t5, 0x38($sp)
/* C7740 800C6B40 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7744 800C6B44 24050013 */  addiu      $a1, $zero, 0x13
/* C7748 800C6B48 24060013 */  addiu      $a2, $zero, 0x13
/* C774C 800C6B4C 24070000 */  addiu      $a3, $zero, 0x0
/* C7750 800C6B50 AFA00010 */  sw         $zero, 0x10($sp)
/* C7754 800C6B54 AFA80014 */  sw         $t0, 0x14($sp)
/* C7758 800C6B58 0C03189D */  jal        gzip_huft_build
/* C775C 800C6B5C AFA90018 */   sw        $t1, 0x18($sp)
/* C7760 800C6B60 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
/* C7764 800C6B64 8D2D0000 */  lw         $t5, 0x0($t1)
/* C7768 800C6B68 3C02800F */  lui        $v0, %hi(gzip_mask_bits)
/* C776C 800C6B6C 2442948C */  addiu      $v0, $v0, %lo(gzip_mask_bits)
/* C7770 800C6B70 000D1840 */  sll        $v1, $t5, 1
/* C7774 800C6B74 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
/* C7778 800C6B78 00431020 */  add        $v0, $v0, $v1 /* handwritten instruction */
/* C777C 800C6B7C 8D0E0000 */  lw         $t6, 0x0($t0)
/* C7780 800C6B80 0230C820 */  add        $t9, $s1, $s0 /* handwritten instruction */
/* C7784 800C6B84 84580000 */  lh         $t8, 0x0($v0)
/* C7788 800C6B88 23AF0044 */  addi       $t7, $sp, 0x44 /* handwritten instruction */
/* C778C 800C6B8C 240A0000 */  addiu      $t2, $zero, 0x0
.L800C6B90:
/* C7790 800C6B90 1320005F */  beqz       $t9, .L800C6D10
/* C7794 800C6B94 026D082B */   sltu      $at, $s3, $t5
/* C7798 800C6B98 50200009 */  beql       $at, $zero, .L800C6BC0
/* C779C 800C6B9C 02581024 */   and       $v0, $s2, $t8
.L800C6BA0:
/* C77A0 800C6BA0 92820000 */  lbu        $v0, 0x0($s4)
/* C77A4 800C6BA4 26940001 */  addiu      $s4, $s4, 0x1
/* C77A8 800C6BA8 02621004 */  sllv       $v0, $v0, $s3
/* C77AC 800C6BAC 26730008 */  addiu      $s3, $s3, 0x8
/* C77B0 800C6BB0 026D082A */  slt        $at, $s3, $t5
/* C77B4 800C6BB4 1420FFFA */  bnez       $at, .L800C6BA0
/* C77B8 800C6BB8 02429025 */   or        $s2, $s2, $v0
/* C77BC 800C6BBC 02581024 */  and        $v0, $s2, $t8
.L800C6BC0:
/* C77C0 800C6BC0 000210C0 */  sll        $v0, $v0, 3
/* C77C4 800C6BC4 01C24821 */  addu       $t1, $t6, $v0
/* C77C8 800C6BC8 95280004 */  lhu        $t0, 0x4($t1)
/* C77CC 800C6BCC 91220001 */  lbu        $v0, 0x1($t1)
/* C77D0 800C6BD0 29010010 */  slti       $at, $t0, 0x10
/* C77D4 800C6BD4 00529006 */  srlv       $s2, $s2, $v0
/* C77D8 800C6BD8 1420001C */  bnez       $at, .L800C6C4C
/* C77DC 800C6BDC 02629822 */   sub       $s3, $s3, $v0 /* handwritten instruction */
/* C77E0 800C6BE0 24010010 */  addiu      $at, $zero, 0x10
/* C77E4 800C6BE4 1101001E */  beq        $t0, $at, .L800C6C60
/* C77E8 800C6BE8 24010011 */   addiu     $at, $zero, 0x11
/* C77EC 800C6BEC 51010033 */  beql       $t0, $at, .L800C6CBC
/* C77F0 800C6BF0 24080003 */   addiu     $t0, $zero, 0x3
/* C77F4 800C6BF4 24080007 */  addiu      $t0, $zero, 0x7
/* C77F8 800C6BF8 0268082B */  sltu       $at, $s3, $t0
/* C77FC 800C6BFC 50200009 */  beql       $at, $zero, .L800C6C24
/* C7800 800C6C00 3249007F */   andi      $t1, $s2, 0x7F
.L800C6C04:
/* C7804 800C6C04 92820000 */  lbu        $v0, 0x0($s4)
/* C7808 800C6C08 26940001 */  addiu      $s4, $s4, 0x1
/* C780C 800C6C0C 02621004 */  sllv       $v0, $v0, $s3
/* C7810 800C6C10 26730008 */  addiu      $s3, $s3, 0x8
/* C7814 800C6C14 0268082A */  slt        $at, $s3, $t0
/* C7818 800C6C18 1420FFFA */  bnez       $at, .L800C6C04
/* C781C 800C6C1C 02429025 */   or        $s2, $s2, $v0
/* C7820 800C6C20 3249007F */  andi       $t1, $s2, 0x7F
.L800C6C24:
/* C7824 800C6C24 2529000B */  addiu      $t1, $t1, 0xB
/* C7828 800C6C28 01129006 */  srlv       $s2, $s2, $t0
/* C782C 800C6C2C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C7830 800C6C30 0329C823 */  subu       $t9, $t9, $t1
.L800C6C34:
/* C7834 800C6C34 2529FFFF */  addiu      $t1, $t1, -0x1
/* C7838 800C6C38 ADE00000 */  sw         $zero, 0x0($t7)
/* C783C 800C6C3C 1520FFFD */  bnez       $t1, .L800C6C34
/* C7840 800C6C40 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7844 800C6C44 08031AE4 */  j          .L800C6B90
/* C7848 800C6C48 240A0000 */   addiu     $t2, $zero, 0x0
.L800C6C4C:
/* C784C 800C6C4C ADE80000 */  sw         $t0, 0x0($t7)
/* C7850 800C6C50 25EF0004 */  addiu      $t7, $t7, 0x4
/* C7854 800C6C54 2739FFFF */  addiu      $t9, $t9, -0x1
/* C7858 800C6C58 08031AE4 */  j          .L800C6B90
/* C785C 800C6C5C 00085025 */   or        $t2, $zero, $t0
.L800C6C60:
/* C7860 800C6C60 24080002 */  addiu      $t0, $zero, 0x2
/* C7864 800C6C64 0268082B */  sltu       $at, $s3, $t0
/* C7868 800C6C68 50200009 */  beql       $at, $zero, .L800C6C90
/* C786C 800C6C6C 32490003 */   andi      $t1, $s2, 0x3
.L800C6C70:
/* C7870 800C6C70 92820000 */  lbu        $v0, 0x0($s4)
/* C7874 800C6C74 26940001 */  addiu      $s4, $s4, 0x1
/* C7878 800C6C78 02621004 */  sllv       $v0, $v0, $s3
/* C787C 800C6C7C 26730008 */  addiu      $s3, $s3, 0x8
/* C7880 800C6C80 0268082A */  slt        $at, $s3, $t0
/* C7884 800C6C84 1420FFFA */  bnez       $at, .L800C6C70
/* C7888 800C6C88 02429025 */   or        $s2, $s2, $v0
/* C788C 800C6C8C 32490003 */  andi       $t1, $s2, 0x3
.L800C6C90:
/* C7890 800C6C90 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C7894 800C6C94 01129006 */  srlv       $s2, $s2, $t0
/* C7898 800C6C98 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C789C 800C6C9C 0329C823 */  subu       $t9, $t9, $t1
.L800C6CA0:
/* C78A0 800C6CA0 2529FFFF */  addiu      $t1, $t1, -0x1
/* C78A4 800C6CA4 ADEA0000 */  sw         $t2, 0x0($t7)
/* C78A8 800C6CA8 1520FFFD */  bnez       $t1, .L800C6CA0
/* C78AC 800C6CAC 25EF0004 */   addiu     $t7, $t7, 0x4
/* C78B0 800C6CB0 08031AE4 */  j          .L800C6B90
/* C78B4 800C6CB4 00000000 */   nop
/* C78B8 800C6CB8 24080003 */  addiu      $t0, $zero, 0x3
.L800C6CBC:
/* C78BC 800C6CBC 0268082B */  sltu       $at, $s3, $t0
/* C78C0 800C6CC0 50200009 */  beql       $at, $zero, .L800C6CE8
/* C78C4 800C6CC4 32490007 */   andi      $t1, $s2, 0x7
.L800C6CC8:
/* C78C8 800C6CC8 92820000 */  lbu        $v0, 0x0($s4)
/* C78CC 800C6CCC 26940001 */  addiu      $s4, $s4, 0x1
/* C78D0 800C6CD0 02621004 */  sllv       $v0, $v0, $s3
/* C78D4 800C6CD4 26730008 */  addiu      $s3, $s3, 0x8
/* C78D8 800C6CD8 0268082A */  slt        $at, $s3, $t0
/* C78DC 800C6CDC 1420FFFA */  bnez       $at, .L800C6CC8
/* C78E0 800C6CE0 02429025 */   or        $s2, $s2, $v0
/* C78E4 800C6CE4 32490007 */  andi       $t1, $s2, 0x7
.L800C6CE8:
/* C78E8 800C6CE8 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
/* C78EC 800C6CEC 01129006 */  srlv       $s2, $s2, $t0
/* C78F0 800C6CF0 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
/* C78F4 800C6CF4 0329C823 */  subu       $t9, $t9, $t1
.L800C6CF8:
/* C78F8 800C6CF8 2529FFFF */  addiu      $t1, $t1, -0x1
/* C78FC 800C6CFC ADE00000 */  sw         $zero, 0x0($t7)
/* C7900 800C6D00 1520FFFD */  bnez       $t1, .L800C6CF8
/* C7904 800C6D04 25EF0004 */   addiu     $t7, $t7, 0x4
/* C7908 800C6D08 08031AE4 */  j          .L800C6B90
/* C790C 800C6D0C 240A0000 */   addiu     $t2, $zero, 0x0
.L800C6D10:
/* C7910 800C6D10 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7914 800C6D14 AC343768 */  sw         $s4, %lo(gzip_inflate_input)($at)
/* C7918 800C6D18 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C791C 800C6D1C 24080009 */  addiu      $t0, $zero, 0x9
/* C7920 800C6D20 AC32AAD0 */  sw         $s2, %lo(gzip_bit_buffer)($at)
/* C7924 800C6D24 AFA80038 */  sw         $t0, 0x38($sp)
/* C7928 800C6D28 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C792C 800C6D2C 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7930 800C6D30 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C7934 800C6D34 24429412 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C7938 800C6D38 23A30034 */  addi       $v1, $sp, 0x34 /* handwritten instruction */
/* C793C 800C6D3C 23A80038 */  addi       $t0, $sp, 0x38 /* handwritten instruction */
/* C7940 800C6D40 AC33AAD4 */  sw         $s3, %lo(gzip_num_bits)($at)
/* C7944 800C6D44 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7948 800C6D48 00112825 */  or         $a1, $zero, $s1
/* C794C 800C6D4C 24060101 */  addiu      $a2, $zero, 0x101
/* C7950 800C6D50 24E793D4 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C7954 800C6D54 AFA20010 */  sw         $v0, 0x10($sp)
/* C7958 800C6D58 AFA30014 */  sw         $v1, 0x14($sp)
/* C795C 800C6D5C 0C03189D */  jal        gzip_huft_build
/* C7960 800C6D60 AFA80018 */   sw        $t0, 0x18($sp)
/* C7964 800C6D64 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7968 800C6D68 00111080 */  sll        $v0, $s1, 2
/* C796C 800C6D6C 24080006 */  addiu      $t0, $zero, 0x6
/* C7970 800C6D70 00822021 */  addu       $a0, $a0, $v0
/* C7974 800C6D74 AFA80040 */  sw         $t0, 0x40($sp)
/* C7978 800C6D78 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C797C 800C6D7C 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C7980 800C6D80 2442946E */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C7984 800C6D84 23A3003C */  addi       $v1, $sp, 0x3C /* handwritten instruction */
/* C7988 800C6D88 23A80040 */  addi       $t0, $sp, 0x40 /* handwritten instruction */
/* C798C 800C6D8C 00102825 */  or         $a1, $zero, $s0
/* C7990 800C6D90 24060000 */  addiu      $a2, $zero, 0x0
/* C7994 800C6D94 24E79432 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C7998 800C6D98 AFA20010 */  sw         $v0, 0x10($sp)
/* C799C 800C6D9C AFA30014 */  sw         $v1, 0x14($sp)
/* C79A0 800C6DA0 0C03189D */  jal        gzip_huft_build
/* C79A4 800C6DA4 AFA80018 */   sw        $t0, 0x18($sp)
/* C79A8 800C6DA8 8FA40034 */  lw         $a0, 0x34($sp)
/* C79AC 800C6DAC 8FA5003C */  lw         $a1, 0x3C($sp)
/* C79B0 800C6DB0 8FA60038 */  lw         $a2, 0x38($sp)
/* C79B4 800C6DB4 0C031C10 */  jal        gzip_inflate_codes
/* C79B8 800C6DB8 8FA70040 */   lw        $a3, 0x40($sp)
/* C79BC 800C6DBC 8FBF0030 */  lw         $ra, 0x30($sp)
/* C79C0 800C6DC0 8FB4002C */  lw         $s4, 0x2C($sp)
/* C79C4 800C6DC4 8FB30028 */  lw         $s3, 0x28($sp)
/* C79C8 800C6DC8 8FB20024 */  lw         $s2, 0x24($sp)
/* C79CC 800C6DCC 8FB10020 */  lw         $s1, 0x20($sp)
/* C79D0 800C6DD0 8FB0001C */  lw         $s0, 0x1C($sp)
/* C79D4 800C6DD4 03E00008 */  jr         $ra
/* C79D8 800C6DD8 27BD0540 */   addiu     $sp, $sp, 0x540
.end gzip_inflate_dynamic

leaf gzip_inflate_fixed
/* C79DC 800C6DDC 27BDFAD0 */  addiu      $sp, $sp, -0x530
/* C79E0 800C6DE0 AFBF001C */  sw         $ra, 0x1C($sp)
/* C79E4 800C6DE4 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C79E8 800C6DE8 24080024 */  addiu      $t0, $zero, 0x24
/* C79EC 800C6DEC 24090008 */  addiu      $t1, $zero, 0x8
.L800C6DF0:
/* C79F0 800C6DF0 2508FFFF */  addiu      $t0, $t0, -0x1
/* C79F4 800C6DF4 AD690000 */  sw         $t1, 0x0($t3)
/* C79F8 800C6DF8 AD690004 */  sw         $t1, 0x4($t3)
/* C79FC 800C6DFC AD690008 */  sw         $t1, 0x8($t3)
/* C7A00 800C6E00 AD69000C */  sw         $t1, 0xC($t3)
/* C7A04 800C6E04 1500FFFA */  bnez       $t0, .L800C6DF0
/* C7A08 800C6E08 256B0010 */   addiu     $t3, $t3, 0x10
/* C7A0C 800C6E0C 2408001C */  addiu      $t0, $zero, 0x1C
/* C7A10 800C6E10 24090009 */  addiu      $t1, $zero, 0x9
.L800C6E14:
/* C7A14 800C6E14 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7A18 800C6E18 AD690000 */  sw         $t1, 0x0($t3)
/* C7A1C 800C6E1C AD690004 */  sw         $t1, 0x4($t3)
/* C7A20 800C6E20 AD690008 */  sw         $t1, 0x8($t3)
/* C7A24 800C6E24 AD69000C */  sw         $t1, 0xC($t3)
/* C7A28 800C6E28 1500FFFA */  bnez       $t0, .L800C6E14
/* C7A2C 800C6E2C 256B0010 */   addiu     $t3, $t3, 0x10
/* C7A30 800C6E30 24080006 */  addiu      $t0, $zero, 0x6
/* C7A34 800C6E34 24090007 */  addiu      $t1, $zero, 0x7
.L800C6E38:
/* C7A38 800C6E38 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7A3C 800C6E3C AD690000 */  sw         $t1, 0x0($t3)
/* C7A40 800C6E40 AD690004 */  sw         $t1, 0x4($t3)
/* C7A44 800C6E44 AD690008 */  sw         $t1, 0x8($t3)
/* C7A48 800C6E48 AD69000C */  sw         $t1, 0xC($t3)
/* C7A4C 800C6E4C 1500FFFA */  bnez       $t0, .L800C6E38
/* C7A50 800C6E50 256B0010 */   addiu     $t3, $t3, 0x10
/* C7A54 800C6E54 24090008 */  addiu      $t1, $zero, 0x8
/* C7A58 800C6E58 AD690000 */  sw         $t1, 0x0($t3)
/* C7A5C 800C6E5C AD690004 */  sw         $t1, 0x4($t3)
/* C7A60 800C6E60 AD690008 */  sw         $t1, 0x8($t3)
/* C7A64 800C6E64 AD69000C */  sw         $t1, 0xC($t3)
/* C7A68 800C6E68 AD690010 */  sw         $t1, 0x10($t3)
/* C7A6C 800C6E6C AD690014 */  sw         $t1, 0x14($t3)
/* C7A70 800C6E70 AD690018 */  sw         $t1, 0x18($t3)
/* C7A74 800C6E74 AD69001C */  sw         $t1, 0x1C($t3)
/* C7A78 800C6E78 24080007 */  addiu      $t0, $zero, 0x7
/* C7A7C 800C6E7C AFA80038 */  sw         $t0, 0x38($sp)
/* C7A80 800C6E80 3C02800F */  lui        $v0, %hi(gzip_cplext)
/* C7A84 800C6E84 3C07800F */  lui        $a3, %hi(gzip_cplens)
/* C7A88 800C6E88 24429412 */  addiu      $v0, $v0, %lo(gzip_cplext)
/* C7A8C 800C6E8C 23A30020 */  addi       $v1, $sp, 0x20 /* handwritten instruction */
/* C7A90 800C6E90 23A80024 */  addi       $t0, $sp, 0x24 /* handwritten instruction */
/* C7A94 800C6E94 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7A98 800C6E98 24050120 */  addiu      $a1, $zero, 0x120
/* C7A9C 800C6E9C 24060101 */  addiu      $a2, $zero, 0x101
/* C7AA0 800C6EA0 24E793D4 */  addiu      $a3, $a3, %lo(gzip_cplens)
/* C7AA4 800C6EA4 AFA20010 */  sw         $v0, 0x10($sp)
/* C7AA8 800C6EA8 AFA30014 */  sw         $v1, 0x14($sp)
/* C7AAC 800C6EAC 0C03189D */  jal        gzip_huft_build
/* C7AB0 800C6EB0 AFA80018 */   sw        $t0, 0x18($sp)
/* C7AB4 800C6EB4 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
/* C7AB8 800C6EB8 2408000A */  addiu      $t0, $zero, 0xA
/* C7ABC 800C6EBC 24090005 */  addiu      $t1, $zero, 0x5
.L800C6EC0:
/* C7AC0 800C6EC0 2508FFFF */  addiu      $t0, $t0, -0x1
/* C7AC4 800C6EC4 AD690000 */  sw         $t1, 0x0($t3)
/* C7AC8 800C6EC8 AD690004 */  sw         $t1, 0x4($t3)
/* C7ACC 800C6ECC AD690008 */  sw         $t1, 0x8($t3)
/* C7AD0 800C6ED0 1500FFFB */  bnez       $t0, .L800C6EC0
/* C7AD4 800C6ED4 256B000C */   addiu     $t3, $t3, 0xC
/* C7AD8 800C6ED8 3C02800F */  lui        $v0, %hi(gzip_cpdext)
/* C7ADC 800C6EDC 3C07800F */  lui        $a3, %hi(gzip_cpdist)
/* C7AE0 800C6EE0 2442946E */  addiu      $v0, $v0, %lo(gzip_cpdext)
/* C7AE4 800C6EE4 23A30028 */  addi       $v1, $sp, 0x28 /* handwritten instruction */
/* C7AE8 800C6EE8 23A8002C */  addi       $t0, $sp, 0x2C /* handwritten instruction */
/* C7AEC 800C6EEC AFA90040 */  sw         $t1, 0x40($sp)
/* C7AF0 800C6EF0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
/* C7AF4 800C6EF4 2405001E */  addiu      $a1, $zero, 0x1E
/* C7AF8 800C6EF8 24060000 */  addiu      $a2, $zero, 0x0
/* C7AFC 800C6EFC 24E79432 */  addiu      $a3, $a3, %lo(gzip_cpdist)
/* C7B00 800C6F00 AFA20010 */  sw         $v0, 0x10($sp)
/* C7B04 800C6F04 AFA30014 */  sw         $v1, 0x14($sp)
/* C7B08 800C6F08 0C03189D */  jal        gzip_huft_build
/* C7B0C 800C6F0C AFA80018 */   sw        $t0, 0x18($sp)
/* C7B10 800C6F10 8FA40020 */  lw         $a0, 0x20($sp)
/* C7B14 800C6F14 8FA50028 */  lw         $a1, 0x28($sp)
/* C7B18 800C6F18 8FA60024 */  lw         $a2, 0x24($sp)
/* C7B1C 800C6F1C 0C031C10 */  jal        gzip_inflate_codes
/* C7B20 800C6F20 8FA7002C */   lw        $a3, 0x2C($sp)
/* C7B24 800C6F24 8FBF001C */  lw         $ra, 0x1C($sp)
/* C7B28 800C6F28 27BD0530 */  addiu      $sp, $sp, 0x530
/* C7B2C 800C6F2C 03E00008 */  jr         $ra
/* C7B30 800C6F30 00000000 */   nop
.end gzip_inflate_fixed

leaf gzip_inflate_stored
/* C7B34 800C6F34 3C0D8013 */  lui        $t5, %hi(gzip_num_bits)
/* C7B38 800C6F38 8DADAAD4 */  lw         $t5, %lo(gzip_num_bits)($t5)
/* C7B3C 800C6F3C 3C0C8013 */  lui        $t4, %hi(gzip_bit_buffer)
/* C7B40 800C6F40 8D8CAAD0 */  lw         $t4, %lo(gzip_bit_buffer)($t4)
/* C7B44 800C6F44 31A80007 */  andi       $t0, $t5, 0x7
/* C7B48 800C6F48 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C7B4C 800C6F4C 010C6006 */  srlv       $t4, $t4, $t0
/* C7B50 800C6F50 24080010 */  addiu      $t0, $zero, 0x10
/* C7B54 800C6F54 3C0F800E */  lui        $t7, %hi(gzip_inflate_input)
/* C7B58 800C6F58 3C0E800E */  lui        $t6, %hi(gzip_inflate_output)
/* C7B5C 800C6F5C 01A8082B */  sltu       $at, $t5, $t0
/* C7B60 800C6F60 8DEF3768 */  lw         $t7, %lo(gzip_inflate_input)($t7)
/* C7B64 800C6F64 10200008 */  beqz       $at, .L800C6F88
/* C7B68 800C6F68 8DCE376C */   lw        $t6, %lo(gzip_inflate_output)($t6)
.L800C6F6C:
/* C7B6C 800C6F6C 91E20000 */  lbu        $v0, 0x0($t7)
/* C7B70 800C6F70 25EF0001 */  addiu      $t7, $t7, 0x1
/* C7B74 800C6F74 01A21004 */  sllv       $v0, $v0, $t5
/* C7B78 800C6F78 25AD0008 */  addiu      $t5, $t5, 0x8
/* C7B7C 800C6F7C 01A8082A */  slt        $at, $t5, $t0
/* C7B80 800C6F80 1420FFFA */  bnez       $at, .L800C6F6C
/* C7B84 800C6F84 01826025 */   or        $t4, $t4, $v0
.L800C6F88:
/* C7B88 800C6F88 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
/* C7B8C 800C6F8C 3189FFFF */  andi       $t1, $t4, 0xFFFF
/* C7B90 800C6F90 01A8082B */  sltu       $at, $t5, $t0
/* C7B94 800C6F94 10200008 */  beqz       $at, .L800C6FB8
/* C7B98 800C6F98 010C6006 */   srlv      $t4, $t4, $t0
.L800C6F9C:
/* C7B9C 800C6F9C 91E20000 */  lbu        $v0, 0x0($t7)
/* C7BA0 800C6FA0 25EF0001 */  addiu      $t7, $t7, 0x1
/* C7BA4 800C6FA4 01A21004 */  sllv       $v0, $v0, $t5
/* C7BA8 800C6FA8 25AD0008 */  addiu      $t5, $t5, 0x8
/* C7BAC 800C6FAC 01A8082A */  slt        $at, $t5, $t0
/* C7BB0 800C6FB0 1420FFFA */  bnez       $at, .L800C6F9C
/* C7BB4 800C6FB4 01826025 */   or        $t4, $t4, $v0
.L800C6FB8:
/* C7BB8 800C6FB8 31220003 */  andi       $v0, $t1, 0x3
/* C7BBC 800C6FBC 010C6006 */  srlv       $t4, $t4, $t0
/* C7BC0 800C6FC0 1040000A */  beqz       $v0, .L800C6FEC
/* C7BC4 800C6FC4 01A86822 */   sub       $t5, $t5, $t0 /* handwritten instruction */
/* C7BC8 800C6FC8 01224822 */  sub        $t1, $t1, $v0 /* handwritten instruction */
.L800C6FCC:
/* C7BCC 800C6FCC 91EA0000 */  lbu        $t2, 0x0($t7)
/* C7BD0 800C6FD0 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C7BD4 800C6FD4 21EF0001 */  addi       $t7, $t7, 0x1 /* handwritten instruction */
/* C7BD8 800C6FD8 21CE0001 */  addi       $t6, $t6, 0x1 /* handwritten instruction */
/* C7BDC 800C6FDC 1440FFFB */  bnez       $v0, .L800C6FCC
/* C7BE0 800C6FE0 A1CAFFFF */   sb        $t2, -0x1($t6)
/* C7BE4 800C6FE4 1120000D */  beqz       $t1, .L800C701C
/* C7BE8 800C6FE8 00000000 */   nop
.L800C6FEC:
/* C7BEC 800C6FEC 91E20000 */  lbu        $v0, 0x0($t7)
/* C7BF0 800C6FF0 2529FFFC */  addiu      $t1, $t1, -0x4
/* C7BF4 800C6FF4 25EF0004 */  addiu      $t7, $t7, 0x4
/* C7BF8 800C6FF8 A1C20000 */  sb         $v0, 0x0($t6)
/* C7BFC 800C6FFC 91E3FFFD */  lbu        $v1, -0x3($t7)
/* C7C00 800C7000 25CE0004 */  addiu      $t6, $t6, 0x4
/* C7C04 800C7004 A1C3FFFD */  sb         $v1, -0x3($t6)
/* C7C08 800C7008 91EAFFFE */  lbu        $t2, -0x2($t7)
/* C7C0C 800C700C A1CAFFFE */  sb         $t2, -0x2($t6)
/* C7C10 800C7010 91EBFFFF */  lbu        $t3, -0x1($t7)
/* C7C14 800C7014 1520FFF5 */  bnez       $t1, .L800C6FEC
/* C7C18 800C7018 A1CBFFFF */   sb        $t3, -0x1($t6)
.L800C701C:
/* C7C1C 800C701C 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7C20 800C7020 AC2F3768 */  sw         $t7, %lo(gzip_inflate_input)($at)
/* C7C24 800C7024 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C7C28 800C7028 AC2E376C */  sw         $t6, %lo(gzip_inflate_output)($at)
/* C7C2C 800C702C 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7C30 800C7030 AC2CAAD0 */  sw         $t4, %lo(gzip_bit_buffer)($at)
/* C7C34 800C7034 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7C38 800C7038 03E00008 */  jr         $ra
/* C7C3C 800C703C AC2DAAD4 */   sw        $t5, %lo(gzip_num_bits)($at)
.end gzip_inflate_stored

leaf gzip_inflate_codes
/* C7C40 800C7040 27BDFFF0 */  addiu      $sp, $sp, -0x10
/* C7C44 800C7044 3C0B800F */  lui        $t3, %hi(gzip_mask_bits)
/* C7C48 800C7048 AFB20008 */  sw         $s2, 0x8($sp)
/* C7C4C 800C704C AFB10004 */  sw         $s1, 0x4($sp)
/* C7C50 800C7050 AFB00000 */  sw         $s0, 0x0($sp)
/* C7C54 800C7054 256B948C */  addiu      $t3, $t3, %lo(gzip_mask_bits)
/* C7C58 800C7058 00061040 */  sll        $v0, $a2, 1
/* C7C5C 800C705C 00074040 */  sll        $t0, $a3, 1
/* C7C60 800C7060 3C12800E */  lui        $s2, %hi(gzip_inflate_input)
/* C7C64 800C7064 3C11800E */  lui        $s1, %hi(gzip_inflate_output)
/* C7C68 800C7068 3C198013 */  lui        $t9, %hi(gzip_bit_buffer)
/* C7C6C 800C706C 3C108013 */  lui        $s0, %hi(gzip_num_bits)
/* C7C70 800C7070 01621821 */  addu       $v1, $t3, $v0
/* C7C74 800C7074 01684821 */  addu       $t1, $t3, $t0
/* C7C78 800C7078 8E523768 */  lw         $s2, %lo(gzip_inflate_input)($s2)
/* C7C7C 800C707C 8E31376C */  lw         $s1, %lo(gzip_inflate_output)($s1)
/* C7C80 800C7080 8F39AAD0 */  lw         $t9, %lo(gzip_bit_buffer)($t9)
/* C7C84 800C7084 8E10AAD4 */  lw         $s0, %lo(gzip_num_bits)($s0)
/* C7C88 800C7088 946D0000 */  lhu        $t5, 0x0($v1)
/* C7C8C 800C708C 952C0000 */  lhu        $t4, 0x0($t1)
.L800C7090:
/* C7C90 800C7090 0206082B */  sltu       $at, $s0, $a2
.L800C7094:
/* C7C94 800C7094 50200009 */  beql       $at, $zero, .L800C70BC
/* C7C98 800C7098 032D1024 */   and       $v0, $t9, $t5
.L800C709C:
/* C7C9C 800C709C 92420000 */  lbu        $v0, 0x0($s2)
/* C7CA0 800C70A0 26520001 */  addiu      $s2, $s2, 0x1
/* C7CA4 800C70A4 02021004 */  sllv       $v0, $v0, $s0
/* C7CA8 800C70A8 26100008 */  addiu      $s0, $s0, 0x8
/* C7CAC 800C70AC 0206082A */  slt        $at, $s0, $a2
/* C7CB0 800C70B0 1420FFFA */  bnez       $at, .L800C709C
/* C7CB4 800C70B4 0322C825 */   or        $t9, $t9, $v0
/* C7CB8 800C70B8 032D1024 */  and        $v0, $t9, $t5
.L800C70BC:
/* C7CBC 800C70BC 000210C0 */  sll        $v0, $v0, 3
/* C7CC0 800C70C0 00827821 */  addu       $t7, $a0, $v0
/* C7CC4 800C70C4 91F80000 */  lbu        $t8, 0x0($t7)
/* C7CC8 800C70C8 2B010011 */  slti       $at, $t8, 0x11
/* C7CCC 800C70CC 5420001A */  bnel       $at, $zero, .L800C7138
/* C7CD0 800C70D0 91E20001 */   lbu       $v0, 0x1($t7)
/* C7CD4 800C70D4 81E30001 */  lb         $v1, 0x1($t7)
.L800C70D8:
/* C7CD8 800C70D8 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C7CDC 800C70DC 02038022 */  sub        $s0, $s0, $v1 /* handwritten instruction */
/* C7CE0 800C70E0 0218082B */  sltu       $at, $s0, $t8
/* C7CE4 800C70E4 10200008 */  beqz       $at, .L800C7108
/* C7CE8 800C70E8 0079C806 */   srlv      $t9, $t9, $v1
.L800C70EC:
/* C7CEC 800C70EC 92420000 */  lbu        $v0, 0x0($s2)
/* C7CF0 800C70F0 26520001 */  addiu      $s2, $s2, 0x1
/* C7CF4 800C70F4 02021004 */  sllv       $v0, $v0, $s0
/* C7CF8 800C70F8 26100008 */  addiu      $s0, $s0, 0x8
/* C7CFC 800C70FC 0218082A */  slt        $at, $s0, $t8
/* C7D00 800C7100 1420FFFA */  bnez       $at, .L800C70EC
/* C7D04 800C7104 0322C825 */   or        $t9, $t9, $v0
.L800C7108:
/* C7D08 800C7108 00181040 */  sll        $v0, $t8, 1
/* C7D0C 800C710C 004B1021 */  addu       $v0, $v0, $t3
/* C7D10 800C7110 94490000 */  lhu        $t1, 0x0($v0)
/* C7D14 800C7114 8DE80004 */  lw         $t0, 0x4($t7)
/* C7D18 800C7118 01394824 */  and        $t1, $t1, $t9
/* C7D1C 800C711C 000948C0 */  sll        $t1, $t1, 3
/* C7D20 800C7120 01097820 */  add        $t7, $t0, $t1 /* handwritten instruction */
/* C7D24 800C7124 91F80000 */  lbu        $t8, 0x0($t7)
/* C7D28 800C7128 2F010011 */  sltiu      $at, $t8, 0x11
/* C7D2C 800C712C 5020FFEA */  beql       $at, $zero, .L800C70D8
/* C7D30 800C7130 81E30001 */   lb        $v1, 0x1($t7)
/* C7D34 800C7134 91E20001 */  lbu        $v0, 0x1($t7)
.L800C7138:
/* C7D38 800C7138 24010010 */  addiu      $at, $zero, 0x10
/* C7D3C 800C713C 0059C806 */  srlv       $t9, $t9, $v0
/* C7D40 800C7140 17010005 */  bne        $t8, $at, .L800C7158
/* C7D44 800C7144 02028022 */   sub       $s0, $s0, $v0 /* handwritten instruction */
/* C7D48 800C7148 95E20004 */  lhu        $v0, 0x4($t7)
/* C7D4C 800C714C 26310001 */  addiu      $s1, $s1, 0x1
/* C7D50 800C7150 08031C24 */  j          .L800C7090
/* C7D54 800C7154 A222FFFF */   sb        $v0, -0x1($s1)
.L800C7158:
/* C7D58 800C7158 2401000F */  addiu      $at, $zero, 0xF
/* C7D5C 800C715C 13010068 */  beq        $t8, $at, .L800C7300
/* C7D60 800C7160 0218082B */   sltu      $at, $s0, $t8
/* C7D64 800C7164 50200009 */  beql       $at, $zero, .L800C718C
/* C7D68 800C7168 00181040 */   sll       $v0, $t8, 1
.L800C716C:
/* C7D6C 800C716C 92420000 */  lbu        $v0, 0x0($s2)
/* C7D70 800C7170 26520001 */  addiu      $s2, $s2, 0x1
/* C7D74 800C7174 02021004 */  sllv       $v0, $v0, $s0
/* C7D78 800C7178 26100008 */  addiu      $s0, $s0, 0x8
/* C7D7C 800C717C 0218082A */  slt        $at, $s0, $t8
/* C7D80 800C7180 1420FFFA */  bnez       $at, .L800C716C
/* C7D84 800C7184 0322C825 */   or        $t9, $t9, $v0
/* C7D88 800C7188 00181040 */  sll        $v0, $t8, 1
.L800C718C:
/* C7D8C 800C718C 004B1021 */  addu       $v0, $v0, $t3
/* C7D90 800C7190 94490000 */  lhu        $t1, 0x0($v0)
/* C7D94 800C7194 95E80004 */  lhu        $t0, 0x4($t7)
/* C7D98 800C7198 02188022 */  sub        $s0, $s0, $t8 /* handwritten instruction */
/* C7D9C 800C719C 0207082B */  sltu       $at, $s0, $a3
/* C7DA0 800C71A0 01394824 */  and        $t1, $t1, $t9
/* C7DA4 800C71A4 0319C806 */  srlv       $t9, $t9, $t8
/* C7DA8 800C71A8 10200008 */  beqz       $at, .L800C71CC
/* C7DAC 800C71AC 01097021 */   addu      $t6, $t0, $t1
.L800C71B0:
/* C7DB0 800C71B0 92420000 */  lbu        $v0, 0x0($s2)
/* C7DB4 800C71B4 26520001 */  addiu      $s2, $s2, 0x1
/* C7DB8 800C71B8 02021004 */  sllv       $v0, $v0, $s0
/* C7DBC 800C71BC 26100008 */  addiu      $s0, $s0, 0x8
/* C7DC0 800C71C0 0207082A */  slt        $at, $s0, $a3
/* C7DC4 800C71C4 1420FFFA */  bnez       $at, .L800C71B0
/* C7DC8 800C71C8 0322C825 */   or        $t9, $t9, $v0
.L800C71CC:
/* C7DCC 800C71CC 01991024 */  and        $v0, $t4, $t9
/* C7DD0 800C71D0 000210C0 */  sll        $v0, $v0, 3
/* C7DD4 800C71D4 00A27821 */  addu       $t7, $a1, $v0
/* C7DD8 800C71D8 91F80000 */  lbu        $t8, 0x0($t7)
/* C7DDC 800C71DC 2B010011 */  slti       $at, $t8, 0x11
/* C7DE0 800C71E0 5420001A */  bnel       $at, $zero, .L800C724C
/* C7DE4 800C71E4 91E20001 */   lbu       $v0, 0x1($t7)
/* C7DE8 800C71E8 91E80001 */  lbu        $t0, 0x1($t7)
.L800C71EC:
/* C7DEC 800C71EC 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
/* C7DF0 800C71F0 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
/* C7DF4 800C71F4 0218082B */  sltu       $at, $s0, $t8
/* C7DF8 800C71F8 10200008 */  beqz       $at, .L800C721C
/* C7DFC 800C71FC 0119C806 */   srlv      $t9, $t9, $t0
.L800C7200:
/* C7E00 800C7200 92420000 */  lbu        $v0, 0x0($s2)
/* C7E04 800C7204 26520001 */  addiu      $s2, $s2, 0x1
/* C7E08 800C7208 02021004 */  sllv       $v0, $v0, $s0
/* C7E0C 800C720C 26100008 */  addiu      $s0, $s0, 0x8
/* C7E10 800C7210 0218082A */  slt        $at, $s0, $t8
/* C7E14 800C7214 1420FFFA */  bnez       $at, .L800C7200
/* C7E18 800C7218 0322C825 */   or        $t9, $t9, $v0
.L800C721C:
/* C7E1C 800C721C 00181040 */  sll        $v0, $t8, 1
/* C7E20 800C7220 004B1021 */  addu       $v0, $v0, $t3
/* C7E24 800C7224 94490000 */  lhu        $t1, 0x0($v0)
/* C7E28 800C7228 8DE80004 */  lw         $t0, 0x4($t7)
/* C7E2C 800C722C 01394824 */  and        $t1, $t1, $t9
/* C7E30 800C7230 000948C0 */  sll        $t1, $t1, 3
/* C7E34 800C7234 01097821 */  addu       $t7, $t0, $t1
/* C7E38 800C7238 91F80000 */  lbu        $t8, 0x0($t7)
/* C7E3C 800C723C 2F010011 */  sltiu      $at, $t8, 0x11
/* C7E40 800C7240 5020FFEA */  beql       $at, $zero, .L800C71EC
/* C7E44 800C7244 91E80001 */   lbu       $t0, 0x1($t7)
/* C7E48 800C7248 91E20001 */  lbu        $v0, 0x1($t7)
.L800C724C:
/* C7E4C 800C724C 02028022 */  sub        $s0, $s0, $v0 /* handwritten instruction */
/* C7E50 800C7250 0218082B */  sltu       $at, $s0, $t8
/* C7E54 800C7254 10200008 */  beqz       $at, .L800C7278
/* C7E58 800C7258 0059C806 */   srlv      $t9, $t9, $v0
.L800C725C:
/* C7E5C 800C725C 92420000 */  lbu        $v0, 0x0($s2)
/* C7E60 800C7260 26520001 */  addiu      $s2, $s2, 0x1
/* C7E64 800C7264 02021004 */  sllv       $v0, $v0, $s0
/* C7E68 800C7268 26100008 */  addiu      $s0, $s0, 0x8
/* C7E6C 800C726C 0218082A */  slt        $at, $s0, $t8
/* C7E70 800C7270 1420FFFA */  bnez       $at, .L800C725C
/* C7E74 800C7274 0322C825 */   or        $t9, $t9, $v0
.L800C7278:
/* C7E78 800C7278 00181040 */  sll        $v0, $t8, 1
/* C7E7C 800C727C 004B1021 */  addu       $v0, $v0, $t3
/* C7E80 800C7280 94490000 */  lhu        $t1, 0x0($v0)
/* C7E84 800C7284 95E30004 */  lhu        $v1, 0x4($t7)
/* C7E88 800C7288 31C20003 */  andi       $v0, $t6, 0x3
/* C7E8C 800C728C 01394824 */  and        $t1, $t1, $t9
/* C7E90 800C7290 02234022 */  sub        $t0, $s1, $v1 /* handwritten instruction */
/* C7E94 800C7294 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
/* C7E98 800C7298 0319C806 */  srlv       $t9, $t9, $t8
/* C7E9C 800C729C 1040000A */  beqz       $v0, .L800C72C8
/* C7EA0 800C72A0 02188022 */   sub       $s0, $s0, $t8 /* handwritten instruction */
/* C7EA4 800C72A4 01C27022 */  sub        $t6, $t6, $v0 /* handwritten instruction */
.L800C72A8:
/* C7EA8 800C72A8 910A0000 */  lbu        $t2, 0x0($t0)
/* C7EAC 800C72AC 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
/* C7EB0 800C72B0 21080001 */  addi       $t0, $t0, 0x1 /* handwritten instruction */
/* C7EB4 800C72B4 22310001 */  addi       $s1, $s1, 0x1 /* handwritten instruction */
/* C7EB8 800C72B8 1440FFFB */  bnez       $v0, .L800C72A8
/* C7EBC 800C72BC A22AFFFF */   sb        $t2, -0x1($s1)
/* C7EC0 800C72C0 51C0FF74 */  beql       $t6, $zero, .L800C7094
/* C7EC4 800C72C4 0206082B */   sltu      $at, $s0, $a2
.L800C72C8:
/* C7EC8 800C72C8 91020000 */  lbu        $v0, 0x0($t0)
/* C7ECC 800C72CC 25CEFFFC */  addiu      $t6, $t6, -0x4
/* C7ED0 800C72D0 25080004 */  addiu      $t0, $t0, 0x4
/* C7ED4 800C72D4 A2220000 */  sb         $v0, 0x0($s1)
/* C7ED8 800C72D8 9103FFFD */  lbu        $v1, -0x3($t0)
/* C7EDC 800C72DC 26310004 */  addiu      $s1, $s1, 0x4
/* C7EE0 800C72E0 A223FFFD */  sb         $v1, -0x3($s1)
/* C7EE4 800C72E4 9109FFFE */  lbu        $t1, -0x2($t0)
/* C7EE8 800C72E8 A229FFFE */  sb         $t1, -0x2($s1)
/* C7EEC 800C72EC 910AFFFF */  lbu        $t2, -0x1($t0)
/* C7EF0 800C72F0 15C0FFF5 */  bnez       $t6, .L800C72C8
/* C7EF4 800C72F4 A22AFFFF */   sb        $t2, -0x1($s1)
/* C7EF8 800C72F8 08031C24 */  j          .L800C7090
/* C7EFC 800C72FC 00000000 */   nop
.L800C7300:
/* C7F00 800C7300 3C01800E */  lui        $at, %hi(gzip_inflate_input)
/* C7F04 800C7304 AC323768 */  sw         $s2, %lo(gzip_inflate_input)($at)
/* C7F08 800C7308 3C01800E */  lui        $at, %hi(gzip_inflate_output)
/* C7F0C 800C730C AC31376C */  sw         $s1, %lo(gzip_inflate_output)($at)
/* C7F10 800C7310 3C018013 */  lui        $at, %hi(gzip_bit_buffer)
/* C7F14 800C7314 AC39AAD0 */  sw         $t9, %lo(gzip_bit_buffer)($at)
/* C7F18 800C7318 3C018013 */  lui        $at, %hi(gzip_num_bits)
/* C7F1C 800C731C AC30AAD4 */  sw         $s0, %lo(gzip_num_bits)($at)
/* C7F20 800C7320 8FB20008 */  lw         $s2, 0x8($sp)
/* C7F24 800C7324 8FB10004 */  lw         $s1, 0x4($sp)
/* C7F28 800C7328 8FB00000 */  lw         $s0, 0x0($sp)
/* C7F2C 800C732C 03E00008 */  jr         $ra
/* C7F30 800C7330 27BD0010 */   addiu     $sp, $sp, 0x10
.end gzip_inflate_codes
